import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateStudentDto, EnrollStudentDto, UpdateStudentDto, UpdateStudentEnrollmentDto } from './students.dto';

const includeStudent = { user: true, studentParents: { include: { parent: { include: { user: { select: { firstName: true, lastName: true, phone: true, email: true } } } } } }, enrollments: { include: { academicYear: true, schoolClass: true, section: true }, orderBy: { createdAt: 'desc' as const } } };
@Injectable()
export class StudentsService {
  constructor(private readonly prisma: PrismaService) {}
  async findAll(schoolId: string | null) { this.requireSchool(schoolId); const students = await this.prisma.student.findMany({ where: { enrollments: { some: { schoolId } } }, include: includeStudent }); return students.map((student) => this.schoolView(student, schoolId)); }
  async findOne(id: string, schoolId: string | null) { this.requireSchool(schoolId); const student = await this.prisma.student.findFirst({ where: { id, enrollments: { some: { schoolId } } }, include: includeStudent }); if (!student) throw new ForbiddenException('You can only access students enrolled in your own school.'); return this.schoolView(student, schoolId); }
  async create(schoolId: string | null, data: CreateStudentDto) { this.requireSchool(schoolId); if (data.schoolId !== schoolId) throw new ForbiddenException('You can only create students for your own school.'); const user = await this.prisma.user.findUnique({ where: { id: data.userId } }); if (!user) throw new NotFoundException('User not found.'); return this.prisma.student.create({ data: { userId: data.userId, studentCode: data.studentCode, gradeLevel: data.gradeLevel, birthDate: data.birthDate ? new Date(data.birthDate) : null, gender: data.gender, status: data.status ?? 'ACTIVE' } }); }
  async update(id: string, schoolId: string | null, data: UpdateStudentDto) { await this.findOne(id, schoolId); this.requireSchool(schoolId); if (data.schoolId !== undefined && data.schoolId !== schoolId) throw new ForbiddenException('A student cannot be moved to another school.'); const { schoolId: _school, admissionNumber, ...studentData } = data; const student = await this.prisma.student.update({ where: { id }, data: { ...studentData, ...(data.birthDate ? { birthDate: new Date(data.birthDate) } : {}) } }); if (admissionNumber !== undefined) { const enrollment = await this.prisma.studentEnrollment.findFirst({ where: { studentId: id, schoolId, status: 'ACTIVE' }, orderBy: { createdAt: 'desc' } }); if (enrollment) await this.prisma.studentEnrollment.update({ where: { id: enrollment.id }, data: { admissionNumber } }); } return student; }
  async remove(id: string, schoolId: string | null) { await this.findOne(id, schoolId); this.requireSchool(schoolId); return this.prisma.studentEnrollment.updateMany({ where: { studentId: id, schoolId, status: 'ACTIVE' }, data: { status: 'WITHDRAWN' } }); }
  async enroll(studentId: string, schoolId: string | null, data: EnrollStudentDto) { this.requireSchool(schoolId); await this.findOne(studentId, schoolId); const academicYear = await this.prisma.academicYear.findFirst({ where: { id: data.academicYearId, schoolId } }); if (!academicYear) throw new NotFoundException('Academic year not found for your school.'); const schoolClass = await this.prisma.schoolClass.findFirst({ where: { id: data.classId, schoolId, academicYearId: data.academicYearId } }); if (!schoolClass) throw new BadRequestException('Class must belong to the selected academic year and school.'); if (data.sectionId && !await this.prisma.section.findFirst({ where: { id: data.sectionId, schoolId, classId: data.classId } })) throw new BadRequestException('Section must belong to the selected class and school.'); if (await this.prisma.studentEnrollment.findUnique({ where: { studentId_schoolId_academicYearId: { studentId, schoolId, academicYearId: data.academicYearId } } })) throw new ConflictException('Student is already enrolled for this academic year and school.'); const previous = await this.prisma.studentEnrollment.findFirst({ where: { studentId, schoolId }, orderBy: { createdAt: 'desc' } }); return this.prisma.studentEnrollment.create({ data: { schoolId, studentId, academicYearId: data.academicYearId, classId: data.classId, sectionId: data.sectionId, admissionNumber: previous?.admissionNumber ?? `ADM-${studentId.slice(0,8)}`, rollNumber: data.rollNumber?.trim() || null }, include: { academicYear: true, schoolClass: true, section: true } }); }
  async findEnrollments(studentId: string, schoolId: string | null) { this.requireSchool(schoolId); await this.findOne(studentId, schoolId); return this.prisma.studentEnrollment.findMany({ where: { studentId, schoolId }, include: { academicYear: true, schoolClass: true, section: true }, orderBy: { createdAt: 'desc' } }); }
  async updateEnrollment(studentId: string, enrollmentId: string, schoolId: string | null, data: UpdateStudentEnrollmentDto) { this.requireSchool(schoolId); await this.findOne(studentId, schoolId); const enrollment = await this.prisma.studentEnrollment.findFirst({ where: { id: enrollmentId, studentId, schoolId } }); if (!enrollment) throw new NotFoundException('Student enrollment not found.'); const classId = data.classId ?? enrollment.classId; const sectionId = data.sectionId !== undefined ? data.sectionId : data.classId !== undefined ? null : enrollment.sectionId; if (!await this.prisma.schoolClass.findFirst({ where: { id: classId, schoolId, academicYearId: enrollment.academicYearId } })) throw new BadRequestException('Class must belong to the enrollment academic year.'); if (sectionId && !await this.prisma.section.findFirst({ where: { id: sectionId, schoolId, classId } })) throw new BadRequestException('Section must belong to the selected class.'); return this.prisma.studentEnrollment.update({ where: { id: enrollmentId }, data: { ...(data.classId !== undefined ? { classId } : {}), ...(data.sectionId !== undefined ? { sectionId } : {}), ...(data.rollNumber !== undefined ? { rollNumber: data.rollNumber.trim() || null } : {}), ...(data.status !== undefined ? { status: data.status } : {}) }, include: { academicYear: true, schoolClass: true, section: true } }); }
  private schoolView(student: any, schoolId: string) { if (student.user) student.user.passwordHash = undefined; const enrollments = (student.enrollments ?? []).filter((enrollment: any) => enrollment.schoolId === schoolId); const studentParents = (student.studentParents ?? []).filter((link: any) => link.status === 'ACTIVE'); return { ...student, schoolId, admissionNumber: enrollments[0]?.admissionNumber ?? null, enrollments, studentParents }; }
  private requireSchool(schoolId: string | null): asserts schoolId is string { if (!schoolId) throw new ForbiddenException('A school account is required.'); }
}
