import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { MarkStaffAttendanceDto, MarkStudentAttendanceDto } from './attendance.dto';
@Injectable()
export class AttendanceService {
  constructor(private readonly prisma: PrismaService) {}
  async markStudents(schoolId: string | null, userId: string, data: MarkStudentAttendanceDto) { this.school(schoolId); if (!Array.isArray(data.records) || !data.records.length) throw new BadRequestException('records must contain at least one attendance entry.'); const date = this.date(data.date); const ids = [...new Set(data.records.map((item) => item.enrollmentId))]; if (ids.length !== data.records.length) throw new BadRequestException('Duplicate enrollment IDs are not allowed.'); const enrollments = await this.prisma.studentEnrollment.findMany({ where: { id: { in: ids }, schoolId, status: 'ACTIVE' } }); if (enrollments.length !== ids.length) throw new NotFoundException('One or more active enrollments were not found for your school.'); await this.prisma.$transaction(data.records.map((item) => this.prisma.studentAttendance.upsert({ where: { enrollmentId_date: { enrollmentId: item.enrollmentId, date } }, update: { status: item.status, remarks: item.remarks ?? null, markedById: userId }, create: { schoolId, enrollmentId: item.enrollmentId, date, status: item.status, remarks: item.remarks ?? null, markedById: userId } }))); return this.listStudents(schoolId, data.date); }
  async listStudents(schoolId: string | null, dateValue?: string, classId?: string, sectionId?: string, fromValue?: string, toValue?: string) { this.school(schoolId); const date = dateValue ? this.date(dateValue) : undefined; const from = fromValue ? this.date(fromValue) : undefined; const to = toValue ? this.date(toValue) : undefined; if (from && to && from > to) throw new BadRequestException('Attendance from date must be before or equal to the to date.'); return this.prisma.studentAttendance.findMany({ where: { schoolId, ...(date ? { date } : from || to ? { date: { ...(from ? { gte: from } : {}), ...(to ? { lte: to } : {}) } } : {}), enrollment: { ...(classId ? { classId } : {}), ...(sectionId ? { sectionId } : {}) } }, include: { enrollment: { include: { student: { include: { user: { select: { id: true, firstName: true, lastName: true } } } }, schoolClass: true, section: true } } }, orderBy: [{ date: 'asc' }, { createdAt: 'asc' }] }); }
  async markStaff(schoolId: string | null, userId: string, data: MarkStaffAttendanceDto) { this.school(schoolId); if (!await this.prisma.staff.findFirst({ where: { id: data.staffId, schoolId } })) throw new NotFoundException('Staff member not found for your school.'); const date = this.date(data.date); return this.prisma.staffAttendance.upsert({ where: { staffId_date: { staffId: data.staffId, date } }, update: { status: data.status, checkIn: data.checkIn ? new Date(data.checkIn) : null, checkOut: data.checkOut ? new Date(data.checkOut) : null, remarks: data.remarks ?? null, markedById: userId }, create: { schoolId, staffId: data.staffId, date, status: data.status, checkIn: data.checkIn ? new Date(data.checkIn) : null, checkOut: data.checkOut ? new Date(data.checkOut) : null, remarks: data.remarks ?? null, markedById: userId }, include: { staff: { include: { user: { select: { id: true, firstName: true, lastName: true } } } } } }); }
  listStaff(schoolId: string | null, dateValue?: string) { this.school(schoolId); const date = dateValue ? this.date(dateValue) : undefined; return this.prisma.staffAttendance.findMany({ where: { schoolId, ...(date ? { date } : {}) }, include: { staff: { include: { user: { select: { id: true, firstName: true, lastName: true } } } } }, orderBy: [{ date: 'desc' }, { createdAt: 'asc' }] }); }
  private school(value: string | null): asserts value is string { if (!value) throw new ForbiddenException('A school account is required.'); }
  private date(value: string) { const date = new Date(value); if (Number.isNaN(date.getTime())) throw new BadRequestException('A valid attendance date is required.'); date.setUTCHours(0, 0, 0, 0); return date; }
}
