export type Status = 'ACTIVE' | 'INACTIVE' | 'SUSPENDED';
export interface School { id: string; name: string; shortName?: string | null; slug: string; address?: string | null; city?: string | null; country?: string | null; phone?: string | null; email?: string | null; website?: string | null }
export interface User { id: string; schoolId: string | null; email?: string; username?: string | null; firstName: string; lastName: string; mustChangePassword: boolean; school?: School | null }
export interface RoleSummary { id: string; name: string; code: string }
export interface Session { token: string; user: User; roles: RoleSummary[]; permissions: string[] }
export interface AcademicYear { id: string; schoolId: string; name: string; startDate?: string | null; endDate?: string | null; isCurrent: boolean; status: string }
export interface Section { id: string; classId: string; name: string; capacity?: number | null; status: string }
export interface SchoolClass { id: string; academicYearId: string; name: string; code?: string | null; capacity?: number | null; status: string; sections: Section[]; classSubjects?: Array<{ subject: Subject }> }
export interface Subject { id: string; schoolId: string; name: string; code: string; description?: string | null; type: 'CORE' | 'ELECTIVE' | 'OPTIONAL'; status: string }
export interface Permission { id: string; code: string; module: string; action: string; name?: string; description?: string | null }
export interface Role { id: string; name: string; code: string; description?: string | null; isSystem: boolean; isActive: boolean; _count?: { userRoles: number; rolePermissions: number } }
export interface Staff { id: string; userId: string; employeeId: string; joiningDate?: string | null; status: Status; user: User & { phone?: string | null; status: Status; roles: Array<{ role: RoleSummary }> } }
export interface Student { id: string; schoolId: string; studentCode: string; admissionNumber?: string | null; gradeLevel?: string | null; birthDate?: string | null; gender?: string | null; status: 'ACTIVE' | 'INACTIVE' | 'GRADUATED'; user: { firstName: string; lastName: string }; enrollments?: Array<{ id: string; academicYear?: AcademicYear; schoolClass?: { name: string }; section?: { name: string } }> }
export interface DashboardSummary { currentAcademicYear: AcademicYear | null; counts: { classes: number; sections: number; subjects: number; staff: number } }
export interface WorkspaceSection { id: string; name: string; studentCount: number; classTeacher: boolean | null; subjectTeacherCount: number; todayAttendance: { present: number; absent: number; late: number; notMarked: number } }
export interface ClassWorkspace { id: string; name: string; sectionCount: number; studentCount: number; classTeacherAssignedCount: number; classTeacherMissingCount: number; sections: WorkspaceSection[] }
export interface SectionStudent { id: string; rollNumber?: string | null; student: { id: string; admissionNumber?: string | null; studentCode: string; birthDate?: string | null; gender?: string | null; user: { firstName: string; lastName: string; phone?: string | null; email?: string | null }; studentParents: Array<{ relationshipType: string; isPrimary: boolean; parent: { user: { firstName: string; lastName: string; phone?: string | null; email?: string | null } } }> } }
export interface SectionDashboard { academicYear: AcademicYear; class: { id: string; name: string }; section: { id: string; name: string }; classTeacher: { teacher: { user: { firstName: string; lastName: string } } } | null; summary: { totalStudents: number; presentToday: number; absentToday: number; lateToday: number; onDutyToday: number; excusedToday: number; notMarkedToday: number; attendancePercentage: number }; subjectTeachers: Array<{ id: string; subject?: Subject | null; teacher: { user: { firstName: string; lastName: string } } }>; subjects: Subject[]; upcomingExams: Array<{ id: string; name: string; startDate?: string | null }>; upcomingEvents: Array<{ id: string; title: string; startsAt: string }>; students: SectionStudent[]; recentStudents: SectionStudent[] }
