import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'; import { Prisma } from '@prisma/client'; import { PrismaService } from '../prisma/prisma.service'; import { AddExamSubjectDto, CreateExamDto, EnterMarksDto } from './exams.dto';
@Injectable() export class ExamsService { constructor(private readonly prisma:PrismaService){}
 async create(schoolId:string|null,data:CreateExamDto){this.school(schoolId);if(!await this.prisma.academicYear.findFirst({where:{id:data.academicYearId,schoolId}}))throw new NotFoundException('Academic year not found.');return this.prisma.exam.create({data:{schoolId,academicYearId:data.academicYearId,name:data.name.trim(),type:data.type.trim().toUpperCase(),startDate:data.startDate?new Date(data.startDate):null,endDate:data.endDate?new Date(data.endDate):null}})}
 list(schoolId:string|null,academicYearId?:string){this.school(schoolId);return this.prisma.exam.findMany({where:{schoolId,...(academicYearId?{academicYearId}:{})},include:{subjects:{include:{schoolClass:true,subject:true}}},orderBy:{createdAt:'desc'}})}
 async addSubject(schoolId:string|null,examId:string,data:AddExamSubjectDto){this.school(schoolId);const exam=await this.prisma.exam.findFirst({where:{id:examId,schoolId}});if(!exam)throw new NotFoundException('Exam not found.');if(data.maximumMarks<=0||data.passingMarks<0||data.passingMarks>data.maximumMarks)throw new BadRequestException('Marks configuration is invalid.');const [schoolClass,subject]=await Promise.all([this.prisma.schoolClass.findFirst({where:{id:data.classId,schoolId,academicYearId:exam.academicYearId}}),this.prisma.classSubject.findFirst({where:{academicYearId:exam.academicYearId,classId:data.classId,subjectId:data.subjectId,schoolId}})]);if(!schoolClass||!subject)throw new BadRequestException('Subject must be assigned to the exam class for this academic year.');return this.prisma.examSubject.create({data:{examId,classId:data.classId,subjectId:data.subjectId,examDate:data.examDate?new Date(data.examDate):null,maximumMarks:new Prisma.Decimal(data.maximumMarks),passingMarks:new Prisma.Decimal(data.passingMarks)},include:{schoolClass:true,subject:true}})}
 async enterMarks(schoolId:string|null,examSubjectId:string,data:EnterMarksDto){this.school(schoolId);if(!Array.isArray(data.records)||!data.records.length)throw new BadRequestException('records must not be empty.');const examSubject=await this.prisma.examSubject.findFirst({where:{id:examSubjectId,exam:{schoolId}},include:{exam:true}});if(!examSubject)throw new NotFoundException('Exam subject not found.');const ids=[...new Set(data.records.map(x=>x.enrollmentId))];const enrollments=await this.prisma.studentEnrollment.findMany({where:{id:{in:ids},schoolId,academicYearId:examSubject.exam.academicYearId,classId:examSubject.classId}});if(enrollments.length!==ids.length)throw new BadRequestException('Every student must be enrolled in the exam class and year.');for(const record of data.records){if(!record.isAbsent&&(record.marksObtained===undefined||record.marksObtained<0||record.marksObtained>Number(examSubject.maximumMarks)))throw new BadRequestException('Marks must be between zero and maximumMarks.');}await this.prisma.$transaction(data.records.map(record=>this.prisma.studentMark.upsert({where:{examSubjectId_enrollmentId:{examSubjectId,enrollmentId:record.enrollmentId}},update:{marksObtained:record.isAbsent?null:new Prisma.Decimal(record.marksObtained!),isAbsent:record.isAbsent??false,remarks:record.remarks??null},create:{examSubjectId,enrollmentId:record.enrollmentId,marksObtained:record.isAbsent?null:new Prisma.Decimal(record.marksObtained!),isAbsent:record.isAbsent??false,remarks:record.remarks??null}})));return this.results(schoolId,examSubject.examId,examSubject.classId)}
 async results(schoolId:string|null,examId:string,classId?:string){this.school(schoolId);const exam=await this.prisma.exam.findFirst({where:{id:examId,schoolId}});if(!exam)throw new NotFoundException('Exam not found.');const marks=await this.prisma.studentMark.findMany({where:{examSubject:{examId,...(classId?{classId}:{})}},include:{examSubject:{include:{subject:true,schoolClass:true}},enrollment:{include:{student:{include:{user:{select:{firstName:true,lastName:true}}}},section:true}}},orderBy:{enrollmentId:'asc'}});return{exam,results:marks.map(mark=>({...mark,percentage:mark.isAbsent?null:Number(mark.marksObtained)/Number(mark.examSubject.maximumMarks)*100,passed:!mark.isAbsent&&Number(mark.marksObtained)>=Number(mark.examSubject.passingMarks)}))}}
 private school(v:string|null):asserts v is string{if(!v)throw new ForbiddenException('A school account is required.')}
}
