'use client';
import { useEffect, useState } from 'react';
import { useAuth } from '../../../lib/auth-context';

export default function ParentLearning(){
  const {session,logout}=useAuth();const [children,setChildren]=useState<any[]>([]),[enrollmentId,setEnrollmentId]=useState(''),[insights,setInsights]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const request=async(path:string)=>{const r=await fetch((process.env.NEXT_PUBLIC_API_URL||'http://localhost:3001/api/v1')+path,{headers:{Authorization:`Bearer ${session?.token}`}});const d=await r.json();if(!r.ok)throw new Error(d.message||'Information could not be loaded.');return d;};
  useEffect(()=>{let active=true;if(!session)return;request('/parent/me/children').then(d=>active&&setChildren(d)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[session?.token]);
  useEffect(()=>{let active=true;setInsights([]);setError('');if(!enrollmentId)return;setLoading(true);request(`/parent/enrollments/${enrollmentId}/academic-insights`).then(d=>active&&setInsights(d)).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[enrollmentId,session?.token]);
  return <main style={{maxWidth:900,margin:'32px auto',padding:20}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h1>Your child’s learning</h1><button className="button secondary" onClick={logout}>Log out</button></header><p>Teacher-reviewed updates and practical next steps.</p>{error&&<p role="alert" className="alert error">{error}</p>}<label className="field">Child and academic year<select value={enrollmentId} onChange={e=>setEnrollmentId(e.target.value)}><option value="">Choose your child</option>{children.flatMap(link=>link.student.enrollments.map((e:any)=><option key={e.id} value={e.id}>{link.student.user.firstName} {link.student.user.lastName} · {e.school.name} · {e.academicYear.name}</option>))}</select></label>{loading?<p role="status">Loading updates…</p>:enrollmentId&&!insights.length?<p>No reviewed learning summaries have been published yet.</p>:insights.map(i=><article className="card" style={{marginTop:20}} key={i.id}><h2>{i.program.name}</h2><small>Published {new Date(i.publishedAt).toLocaleDateString()}</small><p>{i.content.summary}</p>{[['strengths','Strengths'],['needsSupport','Areas for support'],['nextSteps','Next steps']].map(([key,label])=><section key={key}><h3>{label}</h3><ul>{i.content[key].map((v:string,n:number)=><li key={n}>{v}</li>)}</ul></section>)}<p>{i.content.limitations}</p></article>)}</main>;
}
