const {test}=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {writeFile,unlink}=require('node:fs/promises');
const {join}=require('node:path');
const {tmpdir}=require('node:os');
const {PrismaClient}=require('@prisma/client');
const {WorkflowService}=require('../dist/academic-workflow/workflow.service');
const {AcademicScopeService}=require('../dist/ai/academic-scope.service');

test('database academic lifecycle: analyze, review, plan, teach, assess, intervene, publish parent insight', {skip:process.env.DAVI_WORKFLOW_DB_TEST!=='1',timeout:90000}, async()=>{
  const db=new PrismaClient(),unique=randomUUID(),file=join(tmpdir(),`davi-workflow-${unique}.txt`),rollback=new Error('ROLLBACK_WORKFLOW_FIXTURE');
  await writeFile(file,'Unit 1: Numbers\nLesson 1: Counting\nCount ten objects\n');
  try {
    await assert.rejects(db.$transaction(async tx=>{
      const school=await tx.school.create({data:{name:'Workflow integration fixture',slug:`workflow-${unique}`}});
      const admin=await tx.user.create({data:{schoolId:school.id,email:`admin-${unique}@example.invalid`,passwordHash:'fixture-not-a-login',firstName:'Test',lastName:'Admin',mustChangePassword:false}});
      const user={...admin,roles:['school-admin']};
      const year=await tx.academicYear.create({data:{schoolId:school.id,name:'2026',startDate:new Date('2026-01-01'),endDate:new Date('2026-12-31')}});
      const klass=await tx.schoolClass.create({data:{schoolId:school.id,academicYearId:year.id,name:'Class 1'}});
      const section=await tx.section.create({data:{schoolId:school.id,classId:klass.id,name:'A'}});
      const subject=await tx.subject.create({data:{schoolId:school.id,name:'Mathematics',code:'MATH'}});
      await tx.classSubject.create({data:{schoolId:school.id,academicYearId:year.id,classId:klass.id,subjectId:subject.id}});
      const term=await tx.schoolTerm.create({data:{schoolId:school.id,academicYearId:year.id,name:'Term 1',sortOrder:1}});
      const childUser=await tx.user.create({data:{schoolId:school.id,email:`child-${unique}@example.invalid`,passwordHash:'fixture-not-a-login',firstName:'Test',lastName:'Child'}});
      const child=await tx.student.create({data:{userId:childUser.id,studentCode:`test-${unique}`}});
      const enrollment=await tx.studentEnrollment.create({data:{schoolId:school.id,academicYearId:year.id,classId:klass.id,sectionId:section.id,studentId:child.id,admissionNumber:'FIXTURE-1'}});
      const parentUser=await tx.user.create({data:{email:`parent-${unique}@example.invalid`,passwordHash:'fixture-not-a-login',firstName:'Test',lastName:'Parent'}});
      const parent=await tx.parent.create({data:{userId:parentUser.id}});
      await tx.studentParent.create({data:{parentId:parent.id,studentId:child.id,canViewAcademics:true}});
      const syllabus=await tx.syllabus.create({data:{schoolId:school.id,academicYearId:year.id,classId:klass.id,subjectId:subject.id,termId:term.id,version:1,storageKey:file,fileName:'syllabus.txt',fileHash:unique,uploadedById:admin.id}});
      const curriculum={units:[{title:'Numbers',termId:term.id,lessons:[{title:'Counting',topics:[{code:'T1',title:'Counting',subtopics:['Objects'],outcomes:['Count ten objects'],prerequisites:[],periods:1}]}]}]};
      const lesson={title:'Count objects',objectives:['Count ten objects'],materials:['Blocks'],teachingSteps:['Model counting'],activities:['Count blocks'],assessment:'Count independently',homework:'Count household objects',differentiation:'Use tactile objects'};
      const paper={title:'Counting practice',instructions:'Answer each question',questions:[{code:'Q1',topicCode:'T1',outcome:'Count ten objects',prompt:'Count ten blocks',answer:'Ten',marks:10,difficulty:'EASY'}]};
      const summary={summary:'Counting needs further practice.',strengths:[],needsSupport:['Counting'],nextSteps:['Practice with objects'],limitations:'Based on one recorded question.'};
      const ai={structured:async(feature,instructions,input,schema)=>({output:schema.parse(feature==='syllabus_analyzer-v1'?curriculum:feature==='teaching_lesson-v1'?lesson:feature.endsWith('_summary-v1')?summary:paper),model:'mock-no-network',promptVersion:feature,inputTokens:1,outputTokens:1})};
      const client=new Proxy(tx,{get(target,key){return key==='$transaction'?async fn=>fn(tx):target[key];}});
      const service=new WorkflowService(client,new AcademicScopeService(client),ai);
      const created=await service.create(user,{schoolId:school.id,academicYearId:year.id,classId:klass.id,sectionId:section.id,subjectId:subject.id,syllabusId:syllabus.id,name:'Counting program'});
      await service.analyze(user,created.id);
      let program=await service.get(user,created.id);
      const calendar={terms:[{id:term.id,start:'2026-10-05',end:'2026-10-30'}],workingDays:[1,2,3,4,5],holidays:[],unavailableDates:[],weeklySlots:[{weekday:1,start:'09:00',minutes:40}],revisionPeriods:0};
      await service.review(user,created.id,{revision:program.revision,curriculum,calendar});program=await service.get(user,created.id);
      await service.approve(user,created.id,{revision:program.revision});program=await service.get(user,created.id);
      await service.updateCalendar(user,created.id,{revision:program.revision,calendar});program=await service.get(user,created.id);assert.equal(program.status,'APPROVED');
      assert.equal((await service.plan(user,created.id,{revision:program.revision,from:'2026-10-05'})).saved,true);program=await service.get(user,created.id);
      let session=program.sessions[0];await service.generateLesson(user,created.id,session.id);session=(await service.get(user,created.id)).sessions[0];
      await service.reviewLesson(user,created.id,session.id,{revision:session.revision,content:lesson});session=(await service.get(user,created.id)).sessions[0];
      await service.approveLesson(user,created.id,session.id,{revision:session.revision});session=(await service.get(user,created.id)).sessions[0];
      assert.ok(session.lessonPlanId);assert.equal(await tx.lessonPlan.count({where:{id:session.lessonPlanId,status:'APPROVED'}}),1);
      await service.progress(user,created.id,session.id,{revision:session.revision,status:'COMPLETED',notes:'Taught using blocks'});
      let generated=await service.generatePaper(user,created.id,{kind:'HOMEWORK',topicCodes:['T1'],questionCount:1,dueDate:'2026-10-06'});
      await service.reviewPaper(user,created.id,generated.id,{revision:generated.revision,content:paper});generated=(await service.get(user,created.id)).papers[0];
      await service.publishPaper(user,created.id,generated.id,{revision:generated.revision});generated=(await service.get(user,created.id)).papers[0];
      assert.ok(generated.homeworkId);const homework=await tx.homework.findUnique({where:{id:generated.homeworkId},include:{submissions:true}});assert.equal(homework.submissions.length,1);assert.ok(!homework.description.includes('Teacher answer'));
      await service.marks(user,created.id,generated.id,{revision:generated.revision,enrollmentId:enrollment.id,absent:false,scores:[{questionCode:'Q1',marks:4}]});
      const evidence=await service.evidence(user,created.id);assert.equal(evidence[0].topics[0].percentage,40);assert.equal(evidence[0].topics[0].status,'NEEDS_SUPPORT');
      let assessment=await service.generatePaper(user,created.id,{kind:'ASSESSMENT',topicCodes:['T1'],questionCount:1,dueDate:'2026-10-08'});
      await service.reviewPaper(user,created.id,assessment.id,{revision:assessment.revision,content:paper});assessment=await tx.academicPaper.findUnique({where:{id:assessment.id}});
      await service.publishPaper(user,created.id,assessment.id,{revision:assessment.revision});assessment=await tx.academicPaper.findUnique({where:{id:assessment.id}});assert.ok(assessment.examSubjectId);
      await service.marks(user,created.id,assessment.id,{revision:assessment.revision,enrollmentId:enrollment.id,absent:false,scores:[{questionCode:'Q1',marks:4}]});
      const legacyMark=await tx.studentMark.findUnique({where:{examSubjectId_enrollmentId:{examSubjectId:assessment.examSubjectId,enrollmentId:enrollment.id}}});assert.equal(Number(legacyMark.marksObtained),4);
      const intervention=await service.intervention(user,created.id,{enrollmentId:enrollment.id,topicCode:'T1',action:'Practice counting with blocks, then reassess',dueDate:'2026-10-12'});await service.closeIntervention(user,created.id,intervention.id,{outcome:'Practice completed; reassessment scheduled'});
      let insight=await service.insight(user,created.id,{audience:'PARENT',enrollmentId:enrollment.id});assert.deepEqual(await service.parentInsights(parentUser,enrollment.id),[]);
      await service.reviewInsight(user,created.id,insight.id,{revision:insight.revision,content:summary});insight=(await service.get(user,created.id)).insights[0];
      await service.publishInsight(user,created.id,insight.id,{revision:insight.revision});const published=await service.parentInsights(parentUser,enrollment.id);assert.equal(published.length,1);assert.equal(published[0].evidence,undefined);
      await assert.rejects(service.parentInsights(admin,enrollment.id));
      throw rollback;
    },{timeout:60000,maxWait:10000}),error=>error===rollback);
    assert.equal(await db.school.count({where:{slug:`workflow-${unique}`}}),0,'All test records must roll back');
  } finally {await db.$disconnect();await unlink(file);}
});
