import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'; import { Prisma } from '@prisma/client'; import { PrismaService } from '../prisma/prisma.service'; import { CreateTimePeriodDto, CreateTimetableEntryDto } from './timetable.dto';
@Injectable() export class TimetableService { constructor(private readonly prisma: PrismaService) {}
  createPeriod(schoolId: string | null, data: CreateTimePeriodDto) { this.school(schoolId); if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(data.startTime) || !/^([01]\d|2[0-3]):[0-5]\d$/.test(data.endTime) || data.startTime >= data.endTime) throw new BadRequestException('Use valid HH:mm times with startTime before endTime.'); return this.prisma.timePeriod.create({ data: { schoolId, ...data, isBreak: data.isBreak ?? false } }); }
  listPeriods(schoolId: string | null) { this.school(schoolId); return this.prisma.timePeriod.findMany({ where: { schoolId }, orderBy: { sortOrder: 'asc' } }); }
  async createEntry(schoolId: string | null, data: CreateTimetableEntryDto) { this.school(schoolId); if (!Number.isInteger(data.weekday) || data.weekday < 1 || data.weekday > 7) throw new BadRequestException('weekday must be between 1 and 7.'); const [year, schoolClass, section, assignment, period] = await Promise.all([this.prisma.academicYear.findFirst({ where: { id: data.academicYearId, schoolId } }), this.prisma.schoolClass.findFirst({ where: { id: data.classId, schoolId, academicYearId: data.academicYearId } }), this.prisma.section.findFirst({ where: { id: data.sectionId, schoolId, classId: data.classId } }), this.prisma.teacherAcademicAssignment.findFirst({ where: { teacherId: data.teacherId, academicYearId: data.academicYearId, classId: data.classId, subjectId: data.subjectId, schoolId } }), this.prisma.timePeriod.findFirst({ where: { id: data.periodId, schoolId, isBreak: false } })]); if (!year || !schoolClass || !section || !assignment || !period) throw new BadRequestException('Academic year, class, section, subject-teacher assignment, and teaching period must be valid for this school.'); try { return await this.prisma.timetableEntry.create({ data: { schoolId, ...data }, include: { schoolClass: true, section: true, subject: true, teacher: { include: { user: { select: { firstName: true, lastName: true } } } }, period: true } }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new ConflictException('The section or teacher already has a timetable entry in this period.'); throw error; } }
  list(schoolId: string | null, academicYearId?: string, classId?: string, sectionId?: string, teacherId?: string) { this.school(schoolId); return this.prisma.timetableEntry.findMany({ where: { schoolId, ...(academicYearId ? { academicYearId } : {}), ...(classId ? { classId } : {}), ...(sectionId ? { sectionId } : {}), ...(teacherId ? { teacherId } : {}) }, include: { schoolClass: true, section: true, subject: true, teacher: { include: { user: { select: { firstName: true, lastName: true } } } }, period: true }, orderBy: [{ weekday: 'asc' }, { period: { sortOrder: 'asc' } }] }); }
  async remove(schoolId: string | null, id: string) { this.school(schoolId); const entry = await this.prisma.timetableEntry.findFirst({ where: { id, schoolId } }); if (!entry) throw new NotFoundException('Timetable entry not found.'); return this.prisma.timetableEntry.delete({ where: { id } }); }
  private school(value: string | null): asserts value is string { if (!value) throw new ForbiddenException('A school account is required.'); }
}
