'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { ApiError, classWorkspaceApi, staffApi, teacherApi } from '../../../../lib/api'; import { useAcademicYear } from '../../../../lib/academic-year-context'; import { useAuth } from '../../../../lib/auth-context'; import { useToast } from '../../../../lib/toast-context'; import { EmptyState, Field, FormActions, LoadingState, Modal, PageHeader, PermissionGate, StatusBadge } from '../../../../components/ui'; import type { Staff } from '../../../../lib/types';
type Teacher=Awaited<ReturnType<typeof teacherApi.list>>[number];
export default function TeachersPage(){const{session,can}=useAuth();const{selected}=useAcademicYear();const{show}=useToast();const[rows,setRows]=useState<Teacher[]>([]);const[staff,setStaff]=useState<Staff[]>([]);const[open,setOpen]=useState(false);const[selectedTeacher,setSelectedTeacher]=useState<Teacher|null>(null);const[workload,setWorkload]=useState<Record<string,number|string>|null>(null);const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);const[form,setForm]=useState({userId:'',teacherCode:'',specialization:'',qualification:''});
const load=async()=>{if(!session?.user.schoolId)return;setLoading(true);try{const[a,b]=await Promise.all([teacherApi.list(session.token),staffApi.list(session.token,session.user.schoolId)]);setRows(a);setStaff(b)}catch(e){show(e instanceof ApiError?e.message:'Teachers could not be loaded.','error')}finally{setLoading(false)}};useEffect(()=>{void load()},[session?.token]);const save=async(e:FormEvent)=>{e.preventDefault();if(!session?.user.schoolId)return;setBusy(true);try{await teacherApi.create(session.token,{...form,schoolId:session.user.schoolId});show('Teacher profile created.');setOpen(false);await load()}catch(e){show(e instanceof ApiError?e.message:'Teacher could not be created.','error')}finally{setBusy(false)}};
const assignments=async(teacher:Teacher)=>{if(!session||!selected)return;const member=staff.find(s=>s.userId===teacher.userId);if(!member){show('No staff profile is linked to this teacher.','error');return}setSelectedTeacher(teacher);setWorkload(null);try{setWorkload(await classWorkspaceApi.workload(session.token,selected.id,member.id))}catch(e){show(e instanceof ApiError?e.message:'Academic assignments could not be loaded.','error');setSelectedTeacher(null)}};
return <><PageHeader title="Teachers" description="Teaching profiles, academic responsibilities and workload." action={<PermissionGate code="STAFF_CREATE"><button className="button" onClick={()=>setOpen(true)}>+ Add teacher</button></PermissionGate>}/>{loading?<LoadingState/>:!rows.length?<EmptyState title="No teachers created" detail="Add a staff member, then create their teacher profile."/>:<section className="card table-wrap"><table><thead><tr><th>Teacher</th><th>Code</th><th>Specialization</th><th>Status</th><th>Academic assignments</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.user.firstName} {r.user.lastName}</td><td>{r.teacherCode}</td><td>{r.specialization||'—'}</td><td><StatusBadge status={r.status}/></td><td>{selected&&can('TEACHING_TEAM_VIEW')?<button className="text-button" onClick={()=>void assignments(r)}>View workload</button>:<small>Select an academic year</small>}</td></tr>)}</tbody></table></section>}
{open&&<Modal title="Create teacher profile" onClose={()=>setOpen(false)}><form className="form-grid" onSubmit={save}><Field label="Staff member" required><select required value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})}><option value="">Select staff</option>{staff.filter(s=>!rows.some(t=>t.userId===s.userId)).map(s=><option value={s.userId} key={s.id}>{s.user.firstName} {s.user.lastName} · {s.employeeId}</option>)}</select></Field><Field label="Teacher code" required><input required value={form.teacherCode} onChange={e=>setForm({...form,teacherCode:e.target.value})}/></Field><Field label="Specialization"><input value={form.specialization} onChange={e=>setForm({...form,specialization:e.target.value})}/></Field><Field label="Qualification"><input value={form.qualification} onChange={e=>setForm({...form,qualification:e.target.value})}/></Field><FormActions submitting={busy} onCancel={()=>setOpen(false)} label="Create teacher"/></form></Modal>}
{selectedTeacher&&<Modal title={`Academic assignments · ${selectedTeacher.user.firstName} ${selectedTeacher.user.lastName}`} onClose={()=>setSelectedTeacher(null)}>{!workload?<LoadingState/>:<><p className="muted">Workload for {selected?.name}. Multiple classes and subjects are supported.</p><section className="metric-grid">{[['Team responsibilities',workload.teamResponsibilities],['Subject assignments',workload.subjectAssignments],['Primary subjects',workload.primarySubjects],['Support subjects',workload.supportSubjects],['Weekly periods',workload.weeklyTimetablePeriods]].map(([label,value])=><article className="metric-card" key={String(label)}><strong>{String(value||0)}</strong><p>{label}</p></article>)}</section>{Number(workload.weeklyTimetablePeriods||0)>30&&<div className="alert warning">Weekly workload is above the recommended warning threshold. Review the timetable for this teacher.</div>}<button className="button full" onClick={()=>setSelectedTeacher(null)}>Close</button></>}</Modal>}</>}
