ALTER TABLE "ClassSubject"
ADD COLUMN "isMandatory" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "requiredPeriodsPerWeek" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "preferredPeriod" TEXT,
ADD COLUMN "preferredTimeOfDay" TEXT,
ADD COLUMN "maxPeriodsPerDay" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "maxConsecutive" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "requiresConsecutive" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "displayOrder" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "effectiveFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "effectiveTo" TIMESTAMP(3),
ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "configVersion" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "TimetablePlan" ADD CONSTRAINT "TimetablePlan_templateId_fkey"
FOREIGN KEY ("templateId") REFERENCES "PeriodTimingTemplate"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
