'use client';
import { useEffect, useState } from 'react';
import { ApiError, classWorkspaceApi, staffApi, teacherApi } from '../lib/api';
import { useAuth } from '../lib/auth-context'; import { useToast } from '../lib/toast-context'; import type { Staff, Subject } from '../lib/types'; import { EmptyState, LoadingState, StatusBadge } from './ui';

export function SubjectTeacherAllocation({yearId,classId,sectionId,subjects}:{yearId:string;classId:string;sectionId:string;subjects:Subject[]}){const{session,can}=useAuth();const{show}=useToast();const[staff,setStaff]=useState<Staff[]>([]);const[selected,setSelected]=useState<Record<string,string>>({});const[initial,setInitial]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);
const load=async()=>{if(!session?.user.schoolId)return;setLoading(true);try{const[staffRows,teachers,result]=await Promise.all([staffApi.list(session.token,session.user.schoolId),teacherApi.list(session.token),classWorkspaceApi.subjectTeachers(session.token,yearId,classId,sectionId)]);const teachingUsers=new Set(teachers.filter(t=>t.status==='ACTIVE').map(t=>t.userId));setStaff(staffRows.filter(s=>s.status==='ACTIVE'&&teachingUsers.has(s.userId)));const values:Record<string,string>={};for(const row of result.assignments){if(String(row.assignmentRole)==='PRIMARY'&&row.subjectId&&row.staffId)values[String(row.subjectId)]=String(row.staffId)}setSelected(values);setInitial(values)}catch(e){show(e instanceof ApiError?e.message:'Subject teachers could not be loaded.','error')}finally{setLoading(false)}};useEffect(()=>{void load()},[session?.token,yearId,classId,sectionId]);
const save=async()=>{if(!session)return;setBusy(true);try{const assignments=Object.entries(selected).filter(([,staffId])=>staffId).map(([subjectId,staffId])=>({subjectId,staffId,assignmentRole:'PRIMARY'}));await classWorkspaceApi.saveSubjectTeachers(session.token,yearId,classId,sectionId,assignments);setInitial({...selected});show('Subject teachers saved.')}catch(e){show(e instanceof ApiError?e.message:'Subject teachers could not be saved.','error')}finally{setBusy(false)}};const dirty=JSON.stringify(selected)!==JSON.stringify(initial);
if(loading)return <LoadingState label="Loading subject teachers…"/>;return <section className="card"><div className="card-heading"><div><h2>Subjects and teachers</h2><p>Select the teacher responsible for each subject in this section.</p></div><strong>{Object.values(selected).filter(Boolean).length} of {subjects.length} assigned</strong></div>{!subjects.length?<EmptyState title="No subjects assigned" detail="Assign subjects to the parent class first."/>:<div className="table-wrap"><table><thead><tr><th>Subject</th><th>Code</th><th>Type</th><th>Teacher</th><th>Status</th></tr></thead><tbody>{subjects.map(subject=><tr key={subject.id}><td><strong>{subject.name}</strong></td><td>{subject.code}</td><td>{subject.type}</td><td><select aria-label={`Teacher for ${subject.name}`} disabled={!can('SUBJECT_TEACHER_MANAGE')||busy} value={selected[subject.id]||''} onChange={e=>setSelected({...selected,[subject.id]:e.target.value})}><option value="">Select teacher</option>{staff.map(member=><option value={member.id} key={member.id}>{member.user.firstName} {member.user.lastName} · {member.employeeId}</option>)}</select></td><td><StatusBadge status={selected[subject.id]?'ACTIVE':'INACTIVE'}/></td></tr>)}</tbody></table></div>}{can('SUBJECT_TEACHER_MANAGE')?<div className="form-actions"><button className="button secondary" disabled={!dirty||busy} onClick={()=>setSelected({...initial})}>Cancel</button><button className="button" disabled={!dirty||busy} onClick={()=>void save()}>{busy?'Saving…':'Save teacher assignments'}</button></div>:<p className="muted">You have read-only access to subject assignments.</p>}</section>}
