'use client';
import type { FormEvent, ReactNode } from 'react';
import { useAuth } from '../lib/auth-context';
export function PageHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="page-header"><div><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>; }
export function LoadingState({ label = 'Loading…' }: { label?: string }) { return <div className="state"><span className="spinner" />{label}</div>; }
export function EmptyState({ title, detail, action }: { title: string; detail?: string; action?: ReactNode }) { return <div className="empty"><div className="empty-icon">◇</div><h3>{title}</h3>{detail && <p>{detail}</p>}{action}</div>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div className="alert error"><span>{message}</span>{retry && <button className="text-button" onClick={retry}>Try again</button>}</div>; }
export function StatusBadge({ status }: { status: string | boolean }) { const text = typeof status === 'boolean' ? (status ? 'Current' : 'Not current') : status; return <span className={`badge ${String(text).toLowerCase().replace(' ', '-')}`}>{text}</span>; }
export function Field({ label, required, hint, children }: { label: string; required?: boolean; hint?: string; children: ReactNode }) { return <label className="field"><span>{label}{required && <b> *</b>}</span>{children}{hint && <small>{hint}</small>}</label>; }
export function Modal({ title, children, onClose, wide = false }: { title: string; children: ReactNode; onClose: () => void; wide?: boolean }) { return <div className="modal-backdrop" role="presentation" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className={`modal ${wide ? 'wide' : ''}`} role="dialog" aria-modal="true"><header><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close">×</button></header>{children}</section></div>; }
export function FormActions({ submitting, onCancel, label = 'Save' }: { submitting: boolean; onCancel: () => void; label?: string }) { return <div className="form-actions"><button type="button" className="button secondary" onClick={onCancel}>Cancel</button><button className="button" disabled={submitting}>{submitting ? 'Saving…' : label}</button></div>; }
export function ConfirmDialog({ title, detail, confirmLabel = 'Confirm', onConfirm, onClose, busy }: { title: string; detail: string; confirmLabel?: string; onConfirm: () => void; onClose: () => void; busy?: boolean }) { return <Modal title={title} onClose={onClose}><p className="muted">{detail}</p><div className="form-actions"><button className="button secondary" onClick={onClose}>Cancel</button><button className="button danger" disabled={busy} onClick={onConfirm}>{busy ? 'Working…' : confirmLabel}</button></div></Modal>; }
export function PermissionGate({ code, children }: { code: string; children: ReactNode }) { const { can } = useAuth(); return can(code) ? <>{children}</> : null; }
export function SimpleForm({ onSubmit, children, className = '' }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void; children: ReactNode; className?: string }) { return <form className={`form-grid ${className}`} onSubmit={onSubmit}>{children}</form>; }
