'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useAuth } from '../../../../lib/auth-context';
import { useAcademicYear } from '../../../../lib/academic-year-context';
import { classApi } from '../../../../lib/api';
import { Field, PageHeader } from '../../../../components/ui';
import type { SchoolClass, Subject } from '../../../../lib/types';

const base=process.env.NEXT_PUBLIC_API_URL||'http://localhost:3001/api/v1';
const today=()=>new Date().toISOString().slice(0,10);
const lines=(value:string)=>value.split('\n').map(s=>s.trim()).filter(Boolean);
type Call=(path:string,method?:string,body?:unknown)=>Promise<any>;

export default function AcademicPlanner(){
  const {session,can}=useAuth(),{selected}=useAcademicYear();
  const [classes,setClasses]=useState<SchoolClass[]>([]),[subjects,setSubjects]=useState<Subject[]>([]);
  const [classId,setClassId]=useState(''),[sectionId,setSectionId]=useState(''),[subjectId,setSubjectId]=useState('');
  const [programs,setPrograms]=useState<any[]>([]),[terms,setTerms]=useState<any[]>([]),[syllabi,setSyllabi]=useState<any[]>([]);
  const [termId,setTermId]=useState(''),[syllabusId,setSyllabusId]=useState(''),[name,setName]=useState('');
  const [program,setProgram]=useState<any>(null),[tab,setTab]=useState('Curriculum'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const call:Call=async(path,method='GET',body)=>{const response=await fetch(base+path,{method,headers:{Authorization:`Bearer ${session?.token}`,...(body!==undefined?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.message==='string'?data.message:'Request failed. Check your permissions and inputs.');return data;};
  const scope={schoolId:session?.user.schoolId||'',academicYearId:selected?.id||'',classId,sectionId,subjectId};
  const ready=Object.values(scope).every(Boolean);
  useEffect(()=>{let active=true;setProgram(null);setPrograms([]);setClassId('');setSectionId('');setSubjectId('');if(!session||!selected)return;Promise.all([classApi.list(session.token),call(`/syllabi/terms?academicYearId=${selected.id}`)]).then(([c,t])=>{if(active){setClasses(c);setTerms(t);}}).catch(e=>active&&setError(e.message));return()=>{active=false;};},[session?.token,selected?.id]);
  useEffect(()=>{let active=true;setProgram(null);setPrograms([]);if(!session||!selected||!classId)return;classApi.assignedSubjects(session.token,selected.id,classId).then(d=>active&&setSubjects(d.subjects)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[classId,selected?.id]);
  useEffect(()=>{let active=true;setProgram(null);setPrograms([]);if(ready)call('/academic-programs?'+new URLSearchParams(scope)).then(d=>active&&setPrograms(d)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[sectionId,subjectId,classId,selected?.id]);
  useEffect(()=>{let active=true;setSyllabi([]);setSyllabusId('');if(!ready||!termId)return;const {sectionId:unused,...s}=scope;call('/syllabi?'+new URLSearchParams({...s,termId})).then(d=>active&&setSyllabi(d)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[termId,subjectId,classId,sectionId,selected?.id]);
  const run=async(action:()=>Promise<any>)=>{setBusy(true);setError('');setNotice('');try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const reload=async(id=program?.id)=>{if(id)setProgram(await call(`/academic-programs/${id}`));};
  const act=async(path:string,method='POST',body?:unknown)=>{await call(`/academic-programs/${program.id}${path}`,method,body);await reload();};
  return <><PageHeader title="Academic planner" description="Turn a reviewed syllabus into teaching, assessment and evidence-based follow-up."/>
    {error&&<div role="alert" className="alert error">{error}</div>}{notice&&<div role="status" className="alert">{notice}</div>}
    <fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}>
    <section className="card form-grid three">
      <Field label="Class"><select value={classId} onChange={e=>{setClassId(e.target.value);setSectionId('');setSubjectId('');}}><option value="">Choose class</option>{classes.filter(c=>c.academicYearId===selected?.id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
      <Field label="Section"><select value={sectionId} onChange={e=>setSectionId(e.target.value)}><option value="">Choose section</option>{classes.find(c=>c.id===classId)?.sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>
      <Field label="Subject"><select value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">Choose subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>
    </section>
    {ready&&<section className="card" style={{marginTop:16}}><h2>Academic programs</h2><div className="button-row">{programs.map(p=><button className="button secondary" key={p.id} onClick={()=>void run(()=>reload(p.id))}>{p.name} · {p.status}</button>)}</div>
      {can('LESSON_PLAN_MANAGE')&&<details style={{marginTop:16}}><summary>Create program from uploaded syllabus</summary><div className="form-grid two" style={{marginTop:12}}><Field label="Program name"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Mathematics annual plan"/></Field><Field label="Source term"><select value={termId} onChange={e=>setTermId(e.target.value)}><option value="">Choose term</option>{terms.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></Field><Field label="Uploaded syllabus"><select value={syllabusId} onChange={e=>setSyllabusId(e.target.value)}><option value="">Choose syllabus</option>{syllabi.map(s=><option value={s.id} key={s.id}>{s.fileName} · version {s.version} · {s.status}</option>)}</select></Field><button className="button" disabled={!name.trim()||!syllabusId} onClick={()=>void run(async()=>{const p=await call('/academic-programs','POST',{...scope,name,syllabusId});setPrograms(await call('/academic-programs?'+new URLSearchParams(scope)));await reload(p.id);})}>Create program</button></div><p><Link href="/academics/ai-lesson-plans">Upload a syllabus or add a term</Link></p></details>}
    </section>}
    {busy&&<p role="status">Working… AI generation may take up to two minutes.</p>}
    {program&&<><h2>{program.name} <small>· {program.status}</small></h2><div className="tab-list">{['Curriculum','Calendar','Teaching plan','Homework & assessments','Learning gaps','Intelligence'].filter(t=>!['Learning gaps','Intelligence'].includes(t)||can('REPORT_VIEW')).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
      {(tab==='Curriculum'||tab==='Calendar')&&<CurriculumEditor key={program.id+':'+program.revision} program={program} tab={tab} can={can} save={(curriculum:any,calendar:any)=>run(()=>program.status==='APPROVED'?act('/calendar','PATCH',{revision:program.revision,calendar}):act('/review','PATCH',{revision:program.revision,curriculum,calendar}))} analyze={()=>run(()=>act('/analyze'))} approve={()=>run(()=>act('/approve','POST',{revision:program.revision}))}/>}
      {tab==='Teaching plan'&&<TeachingPlan program={program} can={can} run={run} act={act} plan={(from:string)=>run(async()=>{const result=await call(`/academic-programs/${program.id}/plan`,'POST',{revision:program.revision,from});if(!result.saved)setNotice(result.message+' Missing: '+result.shortages.map((s:any)=>`${s.topicCode}: ${s.missingPeriods} periods`).join(', '));else{setNotice(`${result.sessions.length} teaching periods scheduled.`);await reload();}})}/>}
      {tab==='Homework & assessments'&&<Papers program={program} can={can} run={run} act={act}/>}
      {tab==='Learning gaps'&&<Evidence program={program} can={can} call={call} run={run} act={act}/>}
      {tab==='Intelligence'&&<Insights program={program} can={can} run={run} act={act}/>}
    </>}
    </fieldset>
  </>;
}

function CurriculumEditor({program,tab,save,analyze,approve,can}:any){
  const [curriculum,setCurriculum]=useState<any>(structuredClone(program.curriculum)),[calendar,setCalendar]=useState<any>(structuredClone(program.calendar));
  const locked=tab==='Calendar'&&program.status==='APPROVED'?!can('LESSON_PLAN_APPROVE'):program.status!=='DRAFT'||!can('LESSON_PLAN_MANAGE');
  const update=(action:(draft:any)=>void)=>{const next=structuredClone(curriculum);action(next);setCurriculum(next);};
  const changeCalendar=(action:(draft:any)=>void)=>{const next=structuredClone(calendar);action(next);setCalendar(next);};
  return <section className="card"><p>{locked?'Approved curriculum is preserved. Create another program for a new curriculum version.':'Review AI estimates, outcomes and term allocation before approving. Save both curriculum and calendar before approval.'}</p>
    {tab==='Curriculum'?<><div className="button-row">{!locked&&<button className="button" onClick={analyze}>Analyze uploaded syllabus with AI</button>}</div><fieldset disabled={locked} style={{border:0,padding:0}}>
      {curriculum.units.map((unit:any,ui:number)=><details key={ui} open style={{marginTop:20,border:'1px solid #ddd',padding:16,borderRadius:10}}><summary><strong>{unit.title||'New unit'}</strong></summary><div className="form-grid two"><Field label="Unit"><input value={unit.title} onChange={e=>update(d=>d.units[ui].title=e.target.value)}/></Field><Field label="Allocated term"><select value={unit.termId} onChange={e=>update(d=>d.units[ui].termId=e.target.value)}>{program.terms.map((t:any)=><option value={t.id} key={t.id}>{t.name}</option>)}</select></Field></div>
      {unit.lessons.map((lesson:any,li:number)=><div key={li} style={{marginTop:16}}><Field label="Lesson"><input value={lesson.title} onChange={e=>update(d=>d.units[ui].lessons[li].title=e.target.value)}/></Field>
        {lesson.topics.map((topic:any,ti:number)=><div key={ti} className="preview" style={{margin:'12px 0',padding:12}}><div className="form-grid two">{[['code','Topic code'],['title','Topic title']].map(([key,label])=><Field key={key} label={label}><input value={topic[key]} onChange={e=>update(d=>d.units[ui].lessons[li].topics[ti][key]=e.target.value)}/></Field>)}<Field label="Teaching periods"><input type="number" min={1} max={60} value={topic.periods} onChange={e=>update(d=>d.units[ui].lessons[li].topics[ti].periods=Number(e.target.value))}/></Field><Field label="Prerequisite topic codes (comma separated)"><input value={topic.prerequisites.join(', ')} onChange={e=>update(d=>d.units[ui].lessons[li].topics[ti].prerequisites=e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></Field><Field label="Subtopics (one per line)"><textarea value={topic.subtopics.join('\n')} onChange={e=>update(d=>d.units[ui].lessons[li].topics[ti].subtopics=e.target.value.split('\n'))}/></Field><Field label="Learning outcomes (one per line)"><textarea value={topic.outcomes.join('\n')} onChange={e=>update(d=>d.units[ui].lessons[li].topics[ti].outcomes=e.target.value.split('\n'))}/></Field></div><button className="text-button" onClick={()=>update(d=>d.units[ui].lessons[li].topics.splice(ti,1))}>Remove topic</button></div>)}
        <div className="button-row"><button className="button secondary" onClick={()=>update(d=>d.units[ui].lessons[li].topics.push({code:`T_${Date.now()}`,title:'New topic',subtopics:[],outcomes:['Describe the learning outcome'],prerequisites:[],periods:1}))}>Add topic</button><button className="text-button" onClick={()=>update(d=>d.units[ui].lessons.splice(li,1))}>Remove lesson</button></div>
      </div>)}<div className="button-row" style={{marginTop:12}}><button className="button secondary" onClick={()=>update(d=>d.units[ui].lessons.push({title:'New lesson',topics:[]}))}>Add lesson</button><button className="text-button" onClick={()=>update(d=>d.units.splice(ui,1))}>Remove unit</button></div></details>)}
      <button className="button secondary" style={{marginTop:12}} onClick={()=>update(d=>d.units.push({title:'New unit',termId:program.terms[0]?.id||'',lessons:[]}))}>Add unit</button></fieldset></>:
      <fieldset disabled={locked} style={{border:0,padding:0}}><h3>Term dates</h3>{program.terms.map((term:any)=>{const assigned=calendar.terms.find((t:any)=>t.id===term.id);return <div key={term.id} className="form-grid three"><label><input type="checkbox" checked={!!assigned} onChange={e=>changeCalendar(d=>{d.terms=e.target.checked?[...d.terms,{id:term.id,start:today(),end:today()}]:d.terms.filter((t:any)=>t.id!==term.id);})}/> {term.name}</label>{assigned&&<><Field label="Start"><input type="date" value={assigned.start} onChange={e=>changeCalendar(d=>d.terms.find((t:any)=>t.id===term.id).start=e.target.value)}/></Field><Field label="End"><input type="date" value={assigned.end} onChange={e=>changeCalendar(d=>d.terms.find((t:any)=>t.id===term.id).end=e.target.value)}/></Field></>}</div>;})}
      <h3>Working days</h3><div className="button-row">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((day,i)=><label key={day}><input type="checkbox" checked={calendar.workingDays.includes(i+1)} onChange={e=>changeCalendar(d=>d.workingDays=e.target.checked?[...d.workingDays,i+1]:d.workingDays.filter((n:number)=>n!==i+1))}/> {day}</label>)}</div>
      <h3>Holidays</h3>{calendar.holidays.map((h:any,i:number)=><div key={i} className="form-grid three"><input aria-label="Holiday date" type="date" value={h.date} onChange={e=>changeCalendar(d=>d.holidays[i].date=e.target.value)}/><input aria-label="Holiday name" value={h.label} onChange={e=>changeCalendar(d=>d.holidays[i].label=e.target.value)}/><button className="text-button" onClick={()=>changeCalendar(d=>d.holidays.splice(i,1))}>Remove</button></div>)}<button className="button secondary" onClick={()=>changeCalendar(d=>d.holidays.push({date:today(),label:'Holiday'}))}>Add holiday</button>
      <h3>Weekly subject periods</h3><p>A published subject timetable takes precedence. These periods are used when no published timetable exists.</p>{calendar.weeklySlots.map((s:any,i:number)=><div key={i} className="form-grid three"><select aria-label="Weekday" value={s.weekday} onChange={e=>changeCalendar(d=>d.weeklySlots[i].weekday=Number(e.target.value))}>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((v,n)=><option value={n+1} key={v}>{v}</option>)}</select><input aria-label="Period start" type="time" value={s.start} onChange={e=>changeCalendar(d=>d.weeklySlots[i].start=e.target.value)}/><input aria-label="Duration in minutes" type="number" min={10} max={180} value={s.minutes} onChange={e=>changeCalendar(d=>d.weeklySlots[i].minutes=Number(e.target.value))}/><button className="text-button" onClick={()=>changeCalendar(d=>d.weeklySlots.splice(i,1))}>Remove period</button></div>)}<button className="button secondary" onClick={()=>changeCalendar(d=>d.weeklySlots.push({weekday:1,start:'09:00',minutes:40}))}>Add period</button>
      <div className="form-grid two" style={{marginTop:16}}><Field label="Teacher unavailable dates (YYYY-MM-DD, one per line)"><textarea value={calendar.unavailableDates.join('\n')} onChange={e=>changeCalendar(d=>d.unavailableDates=e.target.value.split('\n'))}/></Field><Field label="Reserve revision periods per term"><input type="number" min={0} max={100} value={calendar.revisionPeriods} onChange={e=>changeCalendar(d=>d.revisionPeriods=Number(e.target.value))}/></Field></div></fieldset>}
    {!locked&&<div className="button-row" style={{marginTop:20}}><button className="button" onClick={()=>save(curriculum,{...calendar,unavailableDates:calendar.unavailableDates.filter(Boolean)})}>{program.status==='APPROVED'?'Approve calendar changes':'Save curriculum & calendar review'}</button>{program.status==='DRAFT'&&can('LESSON_PLAN_APPROVE')&&<button className="button secondary" disabled={!program.reviewedAt} onClick={approve}>Approve saved curriculum</button>}</div>}
  </section>;
}

function ContentEditor({content,onChange,disabled=false}:any){return <fieldset disabled={disabled} style={{border:0,padding:0}}>{Object.entries(content).map(([key,value])=><Field key={key} label={key.replace(/([A-Z])/g,' $1')}><textarea rows={Array.isArray(value)?4:3} value={Array.isArray(value)?value.join('\n'):String(value)} onChange={e=>onChange({...content,[key]:Array.isArray(value)?e.target.value.split('\n'):e.target.value})}/></Field>)}</fieldset>;}
function LessonCard({session:s,can,run,act}:any){const [content,setContent]=useState<any>(s.lessonContent),[notes,setNotes]=useState(s.progressNotes||'');return <details className="card" style={{marginTop:12}}><summary><strong>{s.scheduledDate.slice(0,10)} {s.startTime} · {s.title}</strong> · {s.status} · Lesson {s.lessonStatus}</summary><p>{s.minutes} minutes</p>{can('LESSON_PLAN_MANAGE')&&s.lessonStatus!=='APPROVED'&&<button className="button secondary" onClick={()=>run(()=>act(`/sessions/${s.id}/generate`))}>{content?'Regenerate draft':'Generate AI lesson'}</button>}{content&&<><ContentEditor content={content} onChange={setContent} disabled={s.lessonStatus==='APPROVED'||!can('LESSON_PLAN_MANAGE')}/><div className="button-row">{s.lessonStatus!=='APPROVED'&&can('LESSON_PLAN_MANAGE')&&<button className="button" onClick={()=>run(()=>act(`/sessions/${s.id}/review`,'PATCH',{revision:s.revision,content}))}>Save review</button>}{s.lessonStatus==='DRAFT'&&can('LESSON_PLAN_APPROVE')&&<button className="button secondary" disabled={!s.reviewedAt} onClick={()=>run(()=>act(`/sessions/${s.id}/approve`,'POST',{revision:s.revision}))}>Approve saved lesson</button>}</div></>}{can('LESSON_PLAN_MANAGE')&&<><Field label="Teaching progress / reteaching notes"><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></Field><div className="button-row">{['COMPLETED','POSTPONED','RETEACH'].map(status=><button className="button secondary" key={status} disabled={status==='COMPLETED'&&s.lessonStatus!=='APPROVED'} onClick={()=>run(()=>act(`/sessions/${s.id}/progress`,'PATCH',{revision:s.revision,status,notes}))}>{status==='COMPLETED'?'Mark taught':status==='POSTPONED'?'Postpone':'Needs reteaching'}</button>)}</div></>}</details>;}
function TeachingPlan({program,can,run,act,plan}:any){const [from,setFrom]=useState(today()),[week,setWeek]=useState('');const rows=program.sessions.filter((s:any)=>!week||(s.scheduledDate.slice(0,10)>=week&&new Date(s.scheduledDate)<new Date(+new Date(week)+7*86400000)));return <><section className="card"><p>Planning respects term dates, holidays, working days, revision reserves and recorded teaching progress. Reviewed classroom lessons are preserved when replanning.</p><div className="form-grid two"><Field label="Plan remaining teaching from"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field>{can('LESSON_PLAN_MANAGE')&&<button className="button" disabled={program.status!=='APPROVED'} onClick={()=>plan(from)}>Generate / replan remaining periods</button>}<Field label="Show seven days starting (clear for all)"><input type="date" value={week} onChange={e=>setWeek(e.target.value)}/></Field></div><p>{rows.length} teaching periods shown.</p></section>{rows.map((s:any)=><LessonCard key={s.id+':'+s.revision} session={s} can={can} run={run} act={act}/>)}</>;}

function Papers({program,can,run,act}:any){const topics=program.curriculum.units.flatMap((u:any)=>u.lessons.flatMap((l:any)=>l.topics));const [kind,setKind]=useState('HOMEWORK'),[codes,setCodes]=useState<string[]>([]),[count,setCount]=useState(5),[due,setDue]=useState(today());return <><section className="card"><h3>Create a draft</h3><div className="form-grid three"><Field label="Type"><select value={kind} onChange={e=>setKind(e.target.value)}><option value="HOMEWORK">Homework</option><option value="ASSESSMENT">Assessment / question paper</option></select></Field><Field label="Number of questions"><input type="number" min={1} max={30} value={count} onChange={e=>setCount(Number(e.target.value))}/></Field><Field label="Due / assessment date"><input type="date" value={due} onChange={e=>setDue(e.target.value)}/></Field></div><p>Select topics:</p>{topics.map((t:any)=><label key={t.code} style={{display:'block'}}><input type="checkbox" checked={codes.includes(t.code)} onChange={e=>setCodes(e.target.checked?[...codes,t.code]:codes.filter(c=>c!==t.code))}/> {t.title}</label>)}{can('HOMEWORK_MANAGE')&&can('EXAM_CREATE')&&<button className="button" style={{marginTop:12}} disabled={!codes.length||program.status!=='APPROVED'} onClick={()=>run(()=>act('/papers','POST',{kind,topicCodes:codes,questionCount:count,dueDate:due}))}>Generate draft</button>}</section>{program.papers.map((p:any)=><PaperCard key={p.id+':'+p.revision} paper={p} program={program} topics={topics} can={can} run={run} act={act}/>)}</>;}
function printQuestions(content:any){const popup=window.open('', '_blank');if(!popup)return;popup.opener=null;popup.document.title=content.title;const main=popup.document.createElement('main');main.style.cssText='max-width:800px;margin:40px auto;font-family:Arial,sans-serif;line-height:1.6';const heading=popup.document.createElement('h1');heading.textContent=content.title;main.appendChild(heading);const instructions=popup.document.createElement('p');instructions.textContent=content.instructions;main.appendChild(instructions);content.questions.forEach((q:any,i:number)=>{const p=popup.document.createElement('p');p.textContent=(i+1)+'. '+q.prompt+' ('+q.marks+' marks)';p.style.marginBottom='60px';main.appendChild(p);});popup.document.body.appendChild(main);popup.print();}
function PaperCard({paper,program,topics,can,run,act}:any){const [content,setContent]=useState<any>(structuredClone(paper.content)),[student,setStudent]=useState(''),[absent,setAbsent]=useState(false),[scores,setScores]=useState<Record<string,string>>({});const writable=paper.status==='DRAFT'&&can('HOMEWORK_MANAGE')&&can('EXAM_UPDATE');return <details className="card" style={{marginTop:16}}><summary><strong>{paper.content.title}</strong> · {paper.kind} · {paper.status}</summary><fieldset disabled={!writable} style={{border:0,padding:0}}><Field label="Title"><input value={content.title} onChange={e=>setContent({...content,title:e.target.value})}/></Field><Field label="Instructions"><textarea value={content.instructions} onChange={e=>setContent({...content,instructions:e.target.value})}/></Field>{content.questions.map((q:any,i:number)=>{const update=(key:string,value:any)=>setContent({...content,questions:content.questions.map((x:any,n:number)=>n===i?{...x,[key]:value}:x)});return <div key={q.code} className="preview" style={{marginTop:12,padding:12}}><h4>Question {i+1}</h4><Field label="Topic"><select value={q.topicCode} onChange={e=>{const topic=topics.find((t:any)=>t.code===e.target.value);setContent({...content,questions:content.questions.map((x:any,n:number)=>n===i?{...x,topicCode:topic.code,outcome:topic.outcomes[0]}:x)});}}>{topics.map((t:any)=><option key={t.code} value={t.code}>{t.title}</option>)}</select></Field><Field label="Learning outcome"><select value={q.outcome} onChange={e=>update('outcome',e.target.value)}>{topics.find((t:any)=>t.code===q.topicCode)?.outcomes.map((o:string)=><option key={o}>{o}</option>)}</select></Field><Field label="Question"><textarea value={q.prompt} onChange={e=>update('prompt',e.target.value)}/></Field><Field label="Teacher answer key"><textarea value={q.answer} onChange={e=>update('answer',e.target.value)}/></Field><div className="form-grid two"><Field label="Maximum marks"><input type="number" min={1} max={100} value={q.marks} onChange={e=>update('marks',Number(e.target.value))}/></Field><Field label="Difficulty"><select value={q.difficulty} onChange={e=>update('difficulty',e.target.value)}>{['EASY','MEDIUM','HARD'].map(v=><option key={v}>{v}</option>)}</select></Field></div></div>;})}</fieldset>
    {writable&&<div className="button-row" style={{marginTop:12}}><button className="button" onClick={()=>run(()=>act(`/papers/${paper.id}/review`,'PATCH',{revision:paper.revision,content}))}>Save paper review</button><button className="button secondary" disabled={!paper.reviewedAt} onClick={()=>run(()=>act(`/papers/${paper.id}/publish`,'POST',{revision:paper.revision}))}>Publish saved paper</button></div>}
    {paper.status==='PUBLISHED'&&can('MARKS_UPDATE')&&<section style={{marginTop:20}}><h3>Record question-level marks</h3><Field label="Student"><select value={student} onChange={e=>{setStudent(e.target.value);const result=(paper.results||[]).find((r:any)=>r.enrollmentId===e.target.value);setAbsent(result?.absent||false);setScores(Object.fromEntries((result?.scores||[]).map((s:any)=>[s.questionCode,String(s.marks)])));}}><option value="">Choose student</option>{program.enrollments.map((e:any)=><option value={e.id} key={e.id}>{e.student.user.firstName} {e.student.user.lastName}</option>)}</select></Field><label><input type="checkbox" checked={absent} onChange={e=>setAbsent(e.target.checked)}/> Absent / not submitted</label>{!absent&&paper.content.questions.map((q:any)=><Field key={q.code} label={`${q.code}: ${q.prompt} (out of ${q.marks})`}><input type="number" min={0} max={q.marks} step="0.5" value={scores[q.code]??''} onChange={e=>setScores({...scores,[q.code]:e.target.value})}/></Field>)}<button className="button" disabled={!student||(!absent&&paper.content.questions.some((q:any)=>scores[q.code]===undefined||scores[q.code]===''))} onClick={()=>run(()=>act(`/papers/${paper.id}/marks`,'POST',{revision:paper.revision,enrollmentId:student,absent,scores:absent?[]:paper.content.questions.map((q:any)=>({questionCode:q.code,marks:Number(scores[q.code])}))}))}>Save marks</button><p>{(paper.results||[]).length} students have recorded results.</p></section>}
  </details>;}

function Evidence({program,can,call,run,act}:any){const [evidence,setEvidence]=useState<any[]>([]),[error,setError]=useState(''),[student,setStudent]=useState(''),[topic,setTopic]=useState(''),[action,setAction]=useState(''),[due,setDue]=useState(today());useEffect(()=>{let active=true;call(`/academic-programs/${program.id}/evidence`).then((d:any)=>active&&setEvidence(d)).catch((e:Error)=>active&&setError(e.message));return()=>{active=false;};},[program.id,program.updatedAt]);return <><section className="card"><h3>Learning evidence</h3><p>Below 60% flags a topic for support. Missing or absent results mean no evidence. Attendance is shown separately.</p>{error&&<p role="alert">{error}</p>}{evidence.map(s=><details key={s.enrollmentId}><summary>{s.name} · {s.attendance.presentDays}/{s.attendance.recordedDays} recorded days present</summary><div className="table-wrap"><table><thead><tr><th>Topic</th><th>Score</th><th>Evidence</th><th>Status</th></tr></thead><tbody>{s.topics.map((t:any)=><tr key={t.topicCode}><td>{t.title}{t.outcomes.map((o:any)=><small className="block" key={o.outcome}>{o.outcome}: {o.percentage}%</small>)}</td><td>{t.percentage===null?'—':t.percentage+'%'}</td><td>{t.evidenceCount} questions</td><td>{t.status.replaceAll('_',' ')}</td></tr>)}</tbody></table></div></details>)}</section>
    {can('LESSON_PLAN_MANAGE')&&<section className="card" style={{marginTop:16}}><h3>Plan support / reteaching</h3><div className="form-grid two"><Field label="Student"><select value={student} onChange={e=>setStudent(e.target.value)}><option value="">Choose student</option>{evidence.map(s=><option value={s.enrollmentId} key={s.enrollmentId}>{s.name}</option>)}</select></Field><Field label="Topic"><select value={topic} onChange={e=>setTopic(e.target.value)}><option value="">Choose topic</option>{program.curriculum.units.flatMap((u:any)=>u.lessons.flatMap((l:any)=>l.topics)).map((t:any)=><option key={t.code} value={t.code}>{t.title}</option>)}</select></Field><Field label="Support action"><textarea value={action} onChange={e=>setAction(e.target.value)} placeholder="Small-group practice followed by a short reassessment"/></Field><Field label="Review date"><input type="date" value={due} onChange={e=>setDue(e.target.value)}/></Field></div><button className="button" disabled={!student||!topic||!action.trim()} onClick={()=>run(()=>act('/interventions','POST',{enrollmentId:student,topicCode:topic,action,dueDate:due}))}>Save intervention</button></section>}
    {program.interventions.map((i:any)=><Intervention key={i.id+':'+i.status} item={i} name={program.enrollments.find((e:any)=>e.id===i.enrollmentId)?.student.user.firstName||'Student'} run={run} act={act} can={can}/>)}
  </>;}
function Intervention({item,name,run,act,can}:any){const [outcome,setOutcome]=useState('');return <section className="card" style={{marginTop:12}}><strong>{name} · {item.topicCode} · {item.status}</strong><p>{item.action}</p><p>Review by {item.dueDate.slice(0,10)}</p>{item.status==='OPEN'&&can('LESSON_PLAN_MANAGE')?<><Field label="Outcome / reassessment evidence"><textarea value={outcome} onChange={e=>setOutcome(e.target.value)}/></Field><button className="button secondary" disabled={!outcome.trim()} onClick={()=>run(()=>act(`/interventions/${item.id}`,'PATCH',{outcome}))}>Complete follow-up</button></>:<p>{item.outcome}</p>}</section>;}
function Insights({program,can,run,act}:any){const [audience,setAudience]=useState('TEACHER'),[student,setStudent]=useState('');return <><section className="card"><h3>Reviewed academic intelligence</h3><p>Summaries use recorded evidence. Parent summaries are visible to linked parents only after review and publishing.</p><div className="form-grid two"><Field label="Audience"><select value={audience} onChange={e=>setAudience(e.target.value)}>{['TEACHER','PARENT','ADMIN'].map(a=><option key={a}>{a}</option>)}</select></Field>{audience==='PARENT'&&<Field label="Student"><select value={student} onChange={e=>setStudent(e.target.value)}><option value="">Choose student</option>{program.enrollments.map((e:any)=><option key={e.id} value={e.id}>{e.student.user.firstName} {e.student.user.lastName}</option>)}</select></Field>}</div>{can('COMMUNICATION_MANAGE')&&<button className="button" disabled={audience==='PARENT'&&!student} onClick={()=>run(()=>act('/insights','POST',{audience,...(audience==='PARENT'?{enrollmentId:student}:{})}))}>Generate summary draft</button>}</section>{program.insights.map((i:any)=><InsightCard key={i.id+':'+i.revision} insight={i} can={can} run={run} act={act}/>)}</>;}
function InsightCard({insight,can,run,act}:any){const [content,setContent]=useState(insight.content);return <details className="card" style={{marginTop:12}}><summary>{insight.audience} summary · {insight.status} · {insight.createdAt.slice(0,10)}</summary><ContentEditor content={content} onChange={setContent} disabled={insight.status==='PUBLISHED'||!can('COMMUNICATION_MANAGE')}/>{insight.status==='DRAFT'&&can('COMMUNICATION_MANAGE')&&<div className="button-row"><button className="button" onClick={()=>run(()=>act(`/insights/${insight.id}/review`,'PATCH',{revision:insight.revision,content}))}>Save review</button><button className="button secondary" disabled={!insight.reviewedAt} onClick={()=>run(()=>act(`/insights/${insight.id}/publish`,'POST',{revision:insight.revision}))}>Publish saved summary</button></div>}</details>;}
