'use client';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { ApiError, parentApi, studentApi } from '../../../../lib/api';
import { useAuth } from '../../../../lib/auth-context';
import { useToast } from '../../../../lib/toast-context';
import type { Parent, Student } from '../../../../lib/types';
import { ConfirmDialog, EmptyState, ErrorState, Field, FormActions, LoadingState, Modal, PageHeader, PermissionGate, StatusBadge } from '../../../../components/ui';

const emptyForm={firstName:'',lastName:'',mobile:'',email:'',parentCode:'',occupation:''}; const PAGE_SIZE=10;
export default function ParentsPage(){const{session,can}=useAuth();const{show}=useToast();const[rows,setRows]=useState<Parent[]>([]);const[students,setStudents]=useState<Student[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[query,setQuery]=useState('');const[page,setPage]=useState(1);const[createOpen,setCreateOpen]=useState(false);const[details,setDetails]=useState<Parent|null>(null);const[edit,setEdit]=useState<Parent|null>(null);const[statusTarget,setStatusTarget]=useState<Parent|null>(null);const[unlink,setUnlink]=useState<{parent:Parent;studentId:string;name:string}|null>(null);const[busy,setBusy]=useState(false);const[credentials,setCredentials]=useState<{username:string;temporaryPassword:string}|null>(null);const[form,setForm]=useState(emptyForm);const[linkForm,setLinkForm]=useState({studentId:'',relationshipType:'guardian',isPrimary:false});
const load=async()=>{if(!session)return;setLoading(true);setError('');try{const[p,s]=await Promise.all([parentApi.list(session.token),studentApi.list(session.token)]);setRows(p);setStudents(s);}catch(e){setError(e instanceof ApiError?e.message:'Parents could not be loaded.');}finally{setLoading(false);}};useEffect(()=>{void load();},[session?.token]);
const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter(r=>`${r.user.firstName} ${r.user.lastName} ${r.parentCode} ${r.user.phone||''} ${r.user.email||''}`.toLowerCase().includes(q));},[rows,query]);const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);useEffect(()=>setPage(1),[query]);
const submitCreate=async(e:FormEvent)=>{e.preventDefault();if(!session)return;setBusy(true);try{const r=await parentApi.onboard(session.token,form);setCredentials(r.credentials);setCreateOpen(false);setForm(emptyForm);show(r.verificationRequired?'Existing parent found. Consent verification is required before linking students.':'Parent created.');await load();}catch(e){show(apiMessage(e,'Parent could not be created.'),'error');}finally{setBusy(false);}};
const openEdit=(parent:Parent)=>{setEdit(parent);setForm({firstName:parent.user.firstName,lastName:parent.user.lastName,mobile:parent.user.phone||'',email:realEmail(parent.user.email),parentCode:parent.parentCode,occupation:parent.occupation||''});};
const submitEdit=async(e:FormEvent)=>{e.preventDefault();if(!session||!edit)return;setBusy(true);try{await parentApi.update(session.token,edit.id,form);show('Parent details updated.');setEdit(null);await load();}catch(e){show(apiMessage(e,'Parent could not be updated.'),'error');}finally{setBusy(false);}};
const changeStatus=async()=>{if(!session||!statusTarget)return;setBusy(true);const next=statusTarget.status==='ACTIVE'?'INACTIVE':'ACTIVE';try{await parentApi.update(session.token,statusTarget.id,{status:next});show(`Parent ${next==='ACTIVE'?'activated':'deactivated'}.`);setStatusTarget(null);await load();}catch(e){show(apiMessage(e,'Parent status could not be changed.'),'error');}finally{setBusy(false);}};
const linkStudent=async(e:FormEvent)=>{e.preventDefault();if(!session||!details||!linkForm.studentId)return;setBusy(true);try{await parentApi.linkStudent(session.token,details.id,linkForm);show('Student linked successfully.');const next=await parentApi.get(session.token,details.id);setDetails(next);setLinkForm({studentId:'',relationshipType:'guardian',isPrimary:false});await load();}catch(e){show(apiMessage(e,'Student could not be linked.'),'error');}finally{setBusy(false);}};
const unlinkStudent=async()=>{if(!session||!unlink)return;setBusy(true);try{await parentApi.unlinkStudent(session.token,unlink.parent.id,unlink.studentId);show('Student link removed.');const next=await parentApi.get(session.token,unlink.parent.id);setDetails(next);setUnlink(null);await load();}catch(e){show(apiMessage(e,'Student link could not be removed.'),'error');}finally{setBusy(false);}};
if(loading)return <LoadingState label="Loading parents…"/>;return <><PageHeader title="Parents" description="Manage parent accounts and student relationships." action={<PermissionGate code="PARENT_CREATE"><button className="button" onClick={()=>setCreateOpen(true)}>+ Add parent</button></PermissionGate>}/>{error?<ErrorState message={error} retry={()=>void load()}/>:<><section className="card"><input className="search-input" aria-label="Search parents" placeholder="Search by name, code, mobile or email" value={query} onChange={e=>setQuery(e.target.value)}/></section>{filtered.length===0?<EmptyState title={query?'No matching parents':'No parents found'} detail={query?'Try a different search.':'Create the first parent account to get started.'}/>:<section className="card table-wrap"><table><thead><tr><th>Parent</th><th>Code</th><th>Mobile</th><th>Linked students</th><th>Verification</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><strong>{r.user.firstName} {r.user.lastName}</strong><small className="table-subtitle">{realEmail(r.user.email)||'No email'}</small></td><td>{r.parentCode}</td><td>{r.user.phone||'—'}</td><td>{r.studentParents?.length||0}</td><td><StatusBadge status={r.verificationStatus||'VERIFIED'}/></td><td><StatusBadge status={r.status}/></td><td className="actions"><button className="text-button" onClick={()=>setDetails(r)}>Details</button>{can('PARENT_UPDATE')&&<><button className="text-button" onClick={()=>openEdit(r)}>Edit</button><button className="text-button" onClick={()=>setStatusTarget(r)}>{r.status==='ACTIVE'?'Deactivate':'Activate'}</button></>}</td></tr>)}</tbody></table><div className="pagination"><span>{filtered.length} parent{filtered.length===1?'':'s'}</span><div><button className="button secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {pages}</span><button className="button secondary" disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></section>}</>}
{createOpen&&<ParentForm title="Create parent login" form={form} setForm={setForm} busy={busy} submit={submitCreate} close={()=>setCreateOpen(false)} label="Create parent"/>}{edit&&<ParentForm title="Edit parent" form={form} setForm={setForm} busy={busy} submit={submitEdit} close={()=>setEdit(null)} label="Save parent"/>}
{details&&<Modal title={`${details.user.firstName} ${details.user.lastName}`} onClose={()=>setDetails(null)} wide><div className="detail-grid"><p><strong>Parent code</strong><br/>{details.parentCode}</p><p><strong>Mobile</strong><br/>{details.user.phone||'—'}</p><p><strong>Email</strong><br/>{realEmail(details.user.email)||'—'}</p><p><strong>Occupation</strong><br/>{details.occupation||'—'}</p></div><h3>Linked students</h3>{!details.studentParents?.length?<EmptyState title="No students linked" detail="Select a student below to create a relationship."/>:<div className="linked-list">{details.studentParents.map(link=><div key={link.studentId}><span><strong>{link.student.user.firstName} {link.student.user.lastName}</strong><small>{link.student.studentCode} · {link.relationshipType}{link.isPrimary?' · Primary contact':''}</small></span>{can('PARENT_UPDATE')&&<button className="text-button danger-text" onClick={()=>setUnlink({parent:details,studentId:link.studentId,name:`${link.student.user.firstName} ${link.student.user.lastName}`})}>Unlink</button>}</div>)}</div>}{can('PARENT_UPDATE')&&<form className="form-grid three link-form" onSubmit={linkStudent}><Field label="Student" required><select required value={linkForm.studentId} onChange={e=>setLinkForm({...linkForm,studentId:e.target.value})}><option value="">Search/select student</option>{students.filter(s=>!details.studentParents?.some(l=>l.studentId===s.id)).map(s=><option key={s.id} value={s.id}>{s.user.firstName} {s.user.lastName} ({s.studentCode})</option>)}</select></Field><Field label="Relationship"><select value={linkForm.relationshipType} onChange={e=>setLinkForm({...linkForm,relationshipType:e.target.value})}><option value="father">Father</option><option value="mother">Mother</option><option value="guardian">Guardian</option><option value="other">Other</option></select></Field><label className="checkbox-field"><input type="checkbox" checked={linkForm.isPrimary} onChange={e=>setLinkForm({...linkForm,isPrimary:e.target.checked})}/> Primary contact</label><div className="span-three"><button className="button" disabled={busy||!linkForm.studentId}>{busy?'Linking…':'Link student'}</button></div></form>}</Modal>}
{statusTarget&&<ConfirmDialog title={`${statusTarget.status==='ACTIVE'?'Deactivate':'Activate'} parent?`} detail={`${statusTarget.user.firstName} ${statusTarget.user.lastName} will be marked ${statusTarget.status==='ACTIVE'?'inactive':'active'}.`} confirmLabel={statusTarget.status==='ACTIVE'?'Deactivate':'Activate'} onClose={()=>setStatusTarget(null)} onConfirm={()=>void changeStatus()} busy={busy}/>} {unlink&&<ConfirmDialog title="Unlink student?" detail={`Remove the relationship with ${unlink.name}? The student and parent accounts will remain.`} confirmLabel="Unlink" onClose={()=>setUnlink(null)} onConfirm={()=>void unlinkStudent()} busy={busy}/>} {credentials&&<Modal title="Parent login created" onClose={()=>setCredentials(null)}><p>Share these credentials securely. They are shown only now.</p><p>Username: <strong>{credentials.username}</strong></p><p>Temporary password: <strong>{credentials.temporaryPassword}</strong></p></Modal>}</>}

function ParentForm({title,form,setForm,busy,submit,close,label}:{title:string;form:typeof emptyForm;setForm:(value:typeof emptyForm)=>void;busy:boolean;submit:(e:FormEvent)=>void;close:()=>void;label:string}){return <Modal title={title} onClose={close}><form className="form-grid two" onSubmit={submit}><Field label="First name" required><input required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></Field><Field label="Last name"><input value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></Field><Field label="Mobile" required hint="10-digit Indian mobile number"><input required type="tel" inputMode="numeric" pattern="[6-9][0-9]{9}" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/></Field><Field label="Email"><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Parent code" required><input required value={form.parentCode} onChange={e=>setForm({...form,parentCode:e.target.value})}/></Field><Field label="Occupation"><input value={form.occupation} onChange={e=>setForm({...form,occupation:e.target.value})}/></Field><div className="span-two"><FormActions submitting={busy} onCancel={close} label={label}/></div></form></Modal>}
function realEmail(value?:string|null){return value?.endsWith('@login.davi.local')?'':value||'';}function apiMessage(error:unknown,fallback:string){if(error instanceof ApiError){if(error.status===409)return error.message||'That mobile, email, parent code, or student link already exists.';return error.message;}return fallback;}
