'use client';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { ApiError, classApi, sectionApi, subjectApi } from '../../../../lib/api';
import { useAuth } from '../../../../lib/auth-context';
import { useAcademicYear } from '../../../../lib/academic-year-context';
import { useToast } from '../../../../lib/toast-context';
import { EmptyState, Field, FormActions, LoadingState, Modal, PageHeader, PermissionGate, StatusBadge } from '../../../../components/ui';
import type { SchoolClass, Section, Subject } from '../../../../lib/types';

export default function ClassesPage() {
  const { session, can } = useAuth(); const { selected } = useAcademicYear(); const { show } = useToast();
  const [rows, setRows] = useState<SchoolClass[]>([]); const [subjects, setSubjects] = useState<Subject[]>([]); const [loading, setLoading] = useState(true);
  const [modal, setModal] = useState<'class'|'section'|'bulk'|'subjects'|null>(null); const [target, setTarget] = useState<SchoolClass|Section|null>(null); const [busy, setBusy] = useState(false);
  const [search, setSearch] = useState(''); const [assigned, setAssigned] = useState<string[]>([]); const [draftSubjects, setDraftSubjects] = useState<string[]>([]);
  const [classForm, setClassForm] = useState({name:'',code:'',capacity:'',status:'ACTIVE'}); const [sectionForm, setSectionForm] = useState({name:'',capacity:'',status:'ACTIVE'});
  const [bulk, setBulk] = useState({montessori:false,primary:false,secondary:false,seniorSecondary:false,numberOfSections:1,sectionCapacity:''});
  const load = async () => { if (!session) return; setLoading(true); try { const [classes, master] = await Promise.all([classApi.list(session.token), subjectApi.list(session.token)]); setRows(classes); setSubjects(master.filter(subject => subject.status === 'ACTIVE')); } catch (error) { show(error instanceof ApiError ? error.message : 'Classes could not be loaded.','error'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [session?.token]);
  const visible = useMemo(() => rows.filter(row => row.academicYearId === selected?.id), [rows, selected]);
  const filteredSubjects = useMemo(() => { const query = search.trim().toLowerCase(); return subjects.filter(subject => !query || subject.name.toLowerCase().includes(query) || subject.code.toLowerCase().includes(query)); }, [search, subjects]);
  const toggleSubject = (id:string) => setDraftSubjects(current => current.includes(id) ? current.filter(value => value !== id) : [...current,id]);
  const openClass = (row?:SchoolClass) => { setTarget(row||null); setClassForm(row?{name:row.name,code:row.code||'',capacity:String(row.capacity||''),status:row.status}:{name:'',code:'',capacity:'',status:'ACTIVE'}); setDraftSubjects([]); setSearch(''); setModal('class'); };
  const openSection = (parent:SchoolClass,row?:Section) => { setTarget(row||parent); setSectionForm(row?{name:row.name,capacity:String(row.capacity||''),status:row.status}:{name:'',capacity:'',status:'ACTIVE'}); setModal('section'); };
  const openSubjects = async (row:SchoolClass) => { if(!session||!selected)return; setTarget(row); setBusy(true); setSearch(''); setModal('subjects'); try { const result=await classApi.assignedSubjects(session.token,selected.id,row.id); const ids=result.subjects.map(subject=>subject.id); setAssigned(ids); setDraftSubjects(ids); } catch(error){show(error instanceof ApiError?error.message:'Class subjects could not be loaded.','error');setModal(null);} finally{setBusy(false);} };
  const saveClass = async(event:FormEvent)=>{event.preventDefault();if(!session||!selected)return;setBusy(true);const data={academicYearId:selected.id,name:classForm.name,code:classForm.code||undefined,capacity:classForm.capacity?Number(classForm.capacity):undefined,status:classForm.status,...(!target?{subjectIds:draftSubjects}:{})};try{if(target&&'academicYearId'in target)await classApi.update(session.token,target.id,data);else await classApi.create(session.token,data);show(target?'Class saved.':`Class created with ${draftSubjects.length} subjects.`);setModal(null);await load();}catch(error){show(error instanceof ApiError?error.message:'Class could not be saved.','error');}finally{setBusy(false);}};
  const saveSubjects=async()=>{if(!session||!selected||!target||!('academicYearId'in target))return;const removed=assigned.filter(id=>!draftSubjects.includes(id)).length;if((removed||!draftSubjects.length)&&!window.confirm(!draftSubjects.length?'Remove all subjects from this class? This affects every section.':`Remove ${removed} subject(s) from this class?`))return;setBusy(true);try{const result=await classApi.replaceSubjects(session.token,selected.id,target.id,draftSubjects);const ids=result.subjects.map(subject=>subject.id);setAssigned(ids);setDraftSubjects(ids);show(`Subjects saved for ${target.name}.`);setModal(null);await load();}catch(error){show(error instanceof ApiError?error.message:'Class subjects could not be saved.','error');}finally{setBusy(false);}};
  const saveSection=async(event:FormEvent)=>{event.preventDefault();if(!session||!target)return;setBusy(true);const data={name:sectionForm.name,capacity:sectionForm.capacity?Number(sectionForm.capacity):undefined,status:sectionForm.status};try{if('classId'in target)await sectionApi.update(session.token,target.id,data);else await sectionApi.create(session.token,{...data,classId:target.id});show('Section saved.');setModal(null);await load();}catch(error){show(error instanceof ApiError?error.message:'Section could not be saved.','error');}finally{setBusy(false);}};
  const saveBulk=async(event:FormEvent)=>{event.preventDefault();if(!session||!selected)return;setBusy(true);try{await classApi.bulk(session.token,{...bulk,academicYearId:selected.id,sectionCapacity:bulk.sectionCapacity?Number(bulk.sectionCapacity):undefined});show('Academic structure created.');setModal(null);await load();}catch(error){show(error instanceof ApiError?error.message:'Quick setup failed.','error');}finally{setBusy(false);}};
  const subjectPicker=<><Field label="Search subjects"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Name or code"/></Field><p className="muted">{draftSubjects.length} subject(s) selected. All sections inherit this list.</p><div className="check-list">{filteredSubjects.map(subject=><label key={subject.id}><input type="checkbox" checked={draftSubjects.includes(subject.id)} disabled={modal==='subjects'&&!can('CLASS_SUBJECT_MANAGE')} onChange={()=>toggleSubject(subject.id)}/><span><strong>{subject.name}</strong><small>{subject.code} · {subject.type}</small></span></label>)}</div>{!subjects.length&&<p className="muted">Create active subjects in the school subject master first.</p>}</>;
  return <><PageHeader title="Classes & sections" description={selected?`Academic structure for ${selected.name}`:'Select or create an academic year first.'} action={<div className="button-row"><PermissionGate code="CLASS_CREATE"><button className="button secondary" disabled={!selected} onClick={()=>setModal('bulk')}>Quick academic setup</button><button className="button" disabled={!selected} onClick={()=>openClass()}>+ Create class</button></PermissionGate></div>}/>
  {loading?<LoadingState/>:!selected?<EmptyState title="No academic year selected" detail="Create an academic year before configuring classes."/>:!visible.length?<EmptyState title={`No classes in ${selected.name}`} detail="Create a class manually or use Quick Academic Setup."/>:<div className="class-grid">{visible.map(row=><article className="card class-card" key={row.id}><header><div><span className="eyebrow">CLASS</span><h2>{row.name}</h2>{row.code&&<p>{row.code}</p>}</div><StatusBadge status={row.status}/></header><div className="button-row"><PermissionGate code="CLASS_SUBJECT_VIEW"><button className="button secondary" onClick={()=>void openSubjects(row)}>Assign subjects</button></PermissionGate><PermissionGate code="CLASS_UPDATE"><button className="text-button" onClick={()=>openClass(row)}>Edit class</button></PermissionGate></div><div className="section-heading"><strong>Sections</strong><PermissionGate code="SECTION_CREATE"><button className="text-button" onClick={()=>openSection(row)}>+ Add section</button></PermissionGate></div>{row.sections.length?<div className="section-list">{row.sections.map(section=><button key={section.id} onClick={()=>openSection(row,section)}><span>{section.name}</span><small>{section.capacity?`${section.capacity} seats`:'No capacity set'}</small><StatusBadge status={section.status}/></button>)}</div>:<p className="muted">No sections yet.</p>}</article>)}</div>}
  {modal==='class'&&<Modal title={target?'Edit class':'Create class'} onClose={()=>setModal(null)} wide><form className="form-grid two" onSubmit={saveClass}><Field label="Class name" required><input value={classForm.name} onChange={e=>setClassForm({...classForm,name:e.target.value})} required/></Field><Field label="Code"><input value={classForm.code} onChange={e=>setClassForm({...classForm,code:e.target.value})}/></Field><Field label="Capacity"><input type="number" min="1" value={classForm.capacity} onChange={e=>setClassForm({...classForm,capacity:e.target.value})}/></Field><Field label="Status"><select value={classForm.status} onChange={e=>setClassForm({...classForm,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></Field>{!target&&<div className="span-two">{subjectPicker}</div>}<div className="span-two"><FormActions submitting={busy} onCancel={()=>setModal(null)}/></div></form></Modal>}
  {modal==='subjects'&&<Modal title={`Subjects · ${target&&'name'in target?target.name:''}`} onClose={()=>setModal(null)} wide>{busy?<LoadingState/>:<>{subjectPicker}{can('CLASS_SUBJECT_MANAGE')?<div className="form-actions"><button className="button secondary" onClick={()=>setModal(null)}>Cancel</button><button className="button" disabled={busy||JSON.stringify([...assigned].sort())===JSON.stringify([...draftSubjects].sort())} onClick={()=>void saveSubjects()}>Save subjects</button></div>:<p className="muted">You have read-only access to class subjects.</p>}</>}</Modal>}
  {modal==='section'&&<Modal title={target&&'classId'in target?'Edit section':'Add section'} onClose={()=>setModal(null)}><form className="form-grid two" onSubmit={saveSection}><Field label="Section name" required><input value={sectionForm.name} onChange={e=>setSectionForm({...sectionForm,name:e.target.value})} required/></Field><Field label="Capacity"><input type="number" min="1" value={sectionForm.capacity} onChange={e=>setSectionForm({...sectionForm,capacity:e.target.value})}/></Field><Field label="Status"><select value={sectionForm.status} onChange={e=>setSectionForm({...sectionForm,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></Field><div className="span-two"><FormActions submitting={busy} onCancel={()=>setModal(null)}/></div></form></Modal>}
  {modal==='bulk'&&<Modal title="Quick academic setup" onClose={()=>setModal(null)} wide><form className="form-grid" onSubmit={saveBulk}><div className="choice-grid">{(['montessori','primary','secondary','seniorSecondary']as const).map(key=><label className={`choice ${bulk[key]?'selected':''}`} key={key}><input type="checkbox" checked={bulk[key]} onChange={e=>setBulk({...bulk,[key]:e.target.checked})}/><strong>{{montessori:'Montessori',primary:'Primary · 1–5',secondary:'Secondary · 6–10',seniorSecondary:'Senior Secondary · 11–12'}[key]}</strong></label>)}</div><div className="form-grid two"><Field label="Sections per class" required><input type="number" min="1" value={bulk.numberOfSections} onChange={e=>setBulk({...bulk,numberOfSections:Number(e.target.value)})}/></Field><Field label="Section capacity"><input type="number" min="1" value={bulk.sectionCapacity} onChange={e=>setBulk({...bulk,sectionCapacity:e.target.value})}/></Field></div><FormActions submitting={busy} onCancel={()=>setModal(null)} label="Create structure"/></form></Modal>}</>;
}
