import{ForbiddenException,Injectable}from'@nestjs/common';import{PrismaService}from'../prisma/prisma.service';
@Injectable()export class DashboardService{
constructor(private readonly p:PrismaService){}
async myDashboard(userId:string,s:string|null){
 if(!s)throw new ForbiddenException('A school account is required.');
 const today=new Date();today.setUTCHours(0,0,0,0);
 const user=await this.p.user.findFirst({where:{id:userId,schoolId:s},include:{teacher:true,student:true}});
 if(user?.teacher){
  const assignments=await this.p.teacherAcademicAssignment.findMany({where:{schoolId:s,teacherId:user.teacher.id,isActive:true,academicYear:{isCurrent:true}},include:{academicYear:true,schoolClass:true,section:true,subject:true},orderBy:[{schoolClass:{name:'asc'}},{section:{name:'asc'}}]});
  const sectionKeys=[...new Map(assignments.filter(a=>a.sectionId).map(a=>[`${a.classId}:${a.sectionId}`,a])).values()];
  const sections=await Promise.all(sectionKeys.map(async a=>{const[students,attendance]=await Promise.all([this.p.studentEnrollment.count({where:{schoolId:s,academicYearId:a.academicYearId,classId:a.classId,sectionId:a.sectionId,status:'ACTIVE'}}),this.p.studentAttendance.groupBy({by:['status'],where:{schoolId:s,date:today,enrollment:{academicYearId:a.academicYearId,classId:a.classId,sectionId:a.sectionId}},_count:{_all:true}})]);const marked=attendance.reduce((n,x)=>n+x._count._all,0);return{academicYearId:a.academicYearId,classId:a.classId,className:a.schoolClass.name,sectionId:a.sectionId!,sectionName:a.section?.name??'',isClassTeacher:assignments.some(x=>x.classId===a.classId&&x.sectionId===a.sectionId&&x.isClassTeacher&&x.isActive),studentCount:students,todayAttendance:{marked,notMarked:Math.max(0,students-marked),byStatus:Object.fromEntries(attendance.map(x=>[x.status,x._count._all]))}};}));
  return{kind:'teacher',teacher:{id:user.teacher.id,teacherCode:user.teacher.teacherCode},assignments:assignments.map(a=>({id:a.id,academicYearId:a.academicYearId,academicYearName:a.academicYear.name,classId:a.classId,className:a.schoolClass.name,sectionId:a.sectionId,sectionName:a.section?.name??null,subjectId:a.subjectId,subjectName:a.subject?.name??null,subjectCode:a.subject?.code??null,isClassTeacher:a.isClassTeacher,responsibilityType:a.responsibilityType,assignmentRole:a.assignmentRole})),sections};
 }
 if(user?.student){
  const enrollment=await this.p.studentEnrollment.findFirst({where:{schoolId:s,studentId:user.student.id,status:'ACTIVE',academicYear:{isCurrent:true}},include:{academicYear:true,schoolClass:true,section:true,attendance:{orderBy:{date:'desc'},take:30}}});
  const totals=enrollment?await this.p.studentAttendance.groupBy({by:['status'],where:{schoolId:s,enrollmentId:enrollment.id},_count:{_all:true}}):[];const marked=totals.reduce((n,x)=>n+x._count._all,0);const present=totals.filter(x=>['PRESENT','LATE','ON_DUTY'].includes(x.status)).reduce((n,x)=>n+x._count._all,0);
  return{kind:'student',student:{id:user.student.id,studentCode:user.student.studentCode,admissionNumber:enrollment?.admissionNumber??null},enrollment:enrollment?{id:enrollment.id,academicYearName:enrollment.academicYear.name,className:enrollment.schoolClass.name,sectionName:enrollment.section?.name??null,rollNumber:enrollment.rollNumber}:null,attendance:{marked,present,percentage:marked?Math.round(present/marked*100):0,byStatus:Object.fromEntries(totals.map(x=>[x.status,x._count._all])),recent:enrollment?.attendance??[]}};
 }
 return{kind:'admin'};
}
async summary(s:string|null){if(!s)throw new ForbiddenException('A school account is required.');const today=new Date();today.setUTCHours(0,0,0,0);const[year,students,staff,teachers,classes,sections,subjects,events,present,absent]=await Promise.all([this.p.academicYear.findFirst({where:{schoolId:s,isCurrent:true}}),this.p.studentEnrollment.count({where:{schoolId:s,status:'ACTIVE',student:{status:'ACTIVE'}}}),this.p.staff.count({where:{schoolId:s,status:'ACTIVE'}}),this.p.teacher.count({where:{schoolId:s,status:'ACTIVE'}}),this.p.schoolClass.count({where:{schoolId:s,status:'ACTIVE'}}),this.p.section.count({where:{schoolId:s,status:'ACTIVE'}}),this.p.subject.count({where:{schoolId:s,status:'ACTIVE'}}),this.p.schoolEvent.findMany({where:{schoolId:s,startsAt:{gte:today},status:'ACTIVE'},orderBy:{startsAt:'asc'},take:5}),this.p.studentAttendance.count({where:{schoolId:s,date:today,status:'PRESENT'}}),this.p.studentAttendance.count({where:{schoolId:s,date:today,status:'ABSENT'}})]);return{currentAcademicYear:year,counts:{students,staff,teachers,classes,sections,subjects},todayAttendance:{present,absent},upcomingEvents:events}}
}
