'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { dashboardApi, roleApi, ApiError } from '../../../lib/api';
import { useAuth } from '../../../lib/auth-context';
import { EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from '../../../components/ui';
import type { DashboardSummary, MyDashboard } from '../../../lib/types';
import { isSuperAdmin } from '../../../lib/auth-context';
import { PlatformDashboard } from '../../../components/platform-dashboard';

export default function DashboardPage(){const{session}=useAuth();return isSuperAdmin(session)?<PlatformDashboard/>:<SchoolUserDashboard/>}
function SchoolUserDashboard(){
 const{session,can}=useAuth();const[view,setView]=useState<MyDashboard|null>(null);const[data,setData]=useState<DashboardSummary|null>(null);const[roles,setRoles]=useState(0);const[error,setError]=useState('');
 const load=async()=>{if(!session)return;setError('');try{const mine=await dashboardApi.me(session.token);setView(mine);if(mine.kind==='admin'){const[summary,roleRows]=await Promise.all([dashboardApi.summary(session.token),can('ROLE_VIEW')&&session.user.schoolId?roleApi.list(session.token,session.user.schoolId):Promise.resolve([])]);setData(summary);setRoles(roleRows.filter(r=>!r.isSystem).length);}}catch(e){setError(e instanceof ApiError?e.message:'Dashboard could not be loaded.');}};
 useEffect(()=>{void load();},[session?.token]);if(!view&&!error)return <LoadingState label="Preparing your dashboard…"/>;if(error)return <ErrorState message={error} retry={load}/>;
 if(view?.kind==='teacher')return <TeacherDashboard view={view} firstName={session?.user.firstName||'Teacher'}/>;
 if(view?.kind==='student')return <StudentDashboard view={view} firstName={session?.user.firstName||'Student'}/>;
 const school=session?.user.school;const steps=[{label:'School Profile',done:Boolean(school?.name),href:'/school/profile'},{label:'Academic Year',done:Boolean(data?.currentAcademicYear),href:'/academics/academic-years'},{label:'Classes',done:Boolean(data?.counts.classes),href:'/academics/classes'},{label:'Sections',done:Boolean(data?.counts.sections),href:'/academics/classes'},{label:'Subjects',done:Boolean(data?.counts.subjects),href:'/academics/subjects'},{label:'Roles',done:roles>0,href:'/access/roles'},{label:'Staff',done:Boolean(data?.counts.staff),href:'/people/staff'}];const completed=steps.filter(s=>s.done).length;
 return <><PageHeader title={`Good day, ${session?.user.firstName||'Administrator'}`} description="Here is your school setup overview."/><section className="hero-card"><div className="school-logo">{(school?.shortName||school?.name||'S').slice(0,2).toUpperCase()}</div><div><span className="eyebrow light">YOUR SCHOOL</span><h2>{school?.name||'School profile'}</h2><p>{data?.currentAcademicYear?`Current academic year · ${data.currentAcademicYear.name}`:'No current academic year selected'}</p></div><Link className="button light" href="/school/profile">View profile</Link></section><section className="metric-grid">{[['Classes',data?.counts.classes||0],['Sections',data?.counts.sections||0],['Subjects',data?.counts.subjects||0],['Staff',data?.counts.staff||0]].map(([label,value])=><Metric label={String(label)} value={value} key={String(label)}/>)}</section><section className="card setup-card"><div className="card-heading"><div><h2>School setup</h2><p>Complete the essentials to get your school ready.</p></div><strong>{completed} of {steps.length}</strong></div><div className="progress"><span style={{width:`${completed/steps.length*100}%`}}/></div><div className="setup-list">{steps.map(step=><Link href={step.href} key={step.label}><span className={step.done?'check done':'check'}>{step.done?'✓':'○'}</span><span>{step.label}</span><span>›</span></Link>)}</div></section></>;
}

function TeacherDashboard({view,firstName}:{view:Extract<MyDashboard,{kind:'teacher'}>;firstName:string}){const subjects=view.assignments.filter(a=>a.subjectId);return <><PageHeader title={`Welcome, ${firstName}`} description="Your assigned classes, subjects, and today's attendance."/><section className="metric-grid"><Metric label="Assigned sections" value={view.sections.length}/><Metric label="Class teacher" value={view.sections.filter(s=>s.isClassTeacher).length}/><Metric label="Subjects" value={new Set(subjects.map(s=>s.subjectId)).size}/><Metric label="Students" value={view.sections.reduce((n,s)=>n+s.studentCount,0)}/></section><section className="card"><div className="card-heading"><div><h2>My classes</h2><p>Class teachers can open their section workspace and manage attendance.</p></div></div>{!view.sections.length?<EmptyState title="No active class assignment" detail="Ask your school administrator to assign you to a class or subject."/>:<div className="teacher-class-grid">{view.sections.map(section=><article className="assignment-card" key={`${section.classId}:${section.sectionId}`}><div><span className="eyebrow">{section.isClassTeacher?'CLASS TEACHER':'SUBJECT TEACHER'}</span><h3>{section.className} · {section.sectionName}</h3><p>{section.studentCount} students</p></div><div className="attendance-mini"><span><strong>{section.todayAttendance.marked}</strong><small>Marked today</small></span><span><strong>{section.todayAttendance.notMarked}</strong><small>Not marked</small></span><span><strong>{section.todayAttendance.byStatus.PRESENT||0}</strong><small>Present</small></span></div>{canOpenClass()&&<Link className="button" href={`/academics/workspace/${section.classId}/sections/${section.sectionId}`}>Open class</Link>}</article>)}</div>}</section><section className="card dashboard-section"><div className="card-heading"><div><h2>My subjects</h2><p>Only subjects assigned to you in the current academic year are shown.</p></div></div>{!subjects.length?<EmptyState title="No subject assignment"/>:<div className="subject-list">{subjects.map(a=><div key={a.id}><span className="subject-code">{a.subjectCode}</span><div><strong>{a.subjectName}</strong><small>{a.className} · {a.sectionName}</small></div><StatusBadge status={a.assignmentRole||'ASSIGNED'}/></div>)}</div>}</section></>}
function canOpenClass(){return true}

function StudentDashboard({view,firstName}:{view:Extract<MyDashboard,{kind:'student'}>;firstName:string}){const a=view.attendance;return <><PageHeader title={`Welcome, ${firstName}`} description="Your class information and attendance record."/>{view.enrollment?<section className="hero-card"><div className="school-logo">{view.enrollment.className.slice(0,2).toUpperCase()}</div><div><span className="eyebrow light">CURRENT CLASS</span><h2>{view.enrollment.className}{view.enrollment.sectionName?` · ${view.enrollment.sectionName}`:''}</h2><p>{view.enrollment.academicYearName}{view.enrollment.rollNumber?` · Roll number ${view.enrollment.rollNumber}`:''}</p></div></section>:<EmptyState title="No active enrollment" detail="Contact the school office to complete your class enrollment."/>}<section className="metric-grid"><Metric label="Attendance" value={`${a.percentage}%`}/><Metric label="Present" value={a.present}/><Metric label="Absent" value={a.byStatus.ABSENT||0}/><Metric label="Days marked" value={a.marked}/></section><section className="card"><div className="card-heading"><div><h2>Recent attendance</h2><p>Your latest 30 attendance records.</p></div></div>{!a.recent.length?<EmptyState title="Attendance has not been marked yet"/>:<div className="table-wrap"><table><thead><tr><th>Date</th><th>Status</th><th>Remarks</th></tr></thead><tbody>{a.recent.map(row=><tr key={row.id}><td>{new Date(row.date).toLocaleDateString()}</td><td><StatusBadge status={row.status}/></td><td>{row.remarks||'—'}</td></tr>)}</tbody></table></div>}</section></>}
function Metric({label,value}:{label:string;value:string|number}){return <article className="metric-card"><span className="metric-icon">•</span><div><strong>{value}</strong><p>{label}</p></div></article>}
