import { BadRequestException,ForbiddenException,Injectable,NotFoundException } from '@nestjs/common';import { Prisma } from '@prisma/client';import { PrismaService } from '../prisma/prisma.service';
@Injectable() export class ClassroomManagementService{constructor(private p:PrismaService){}
private async scope(s:string|null,x:any){if(!s)throw new ForbiddenException('A school account is required.');const section=await this.p.section.findFirst({where:{id:x.sectionId,schoolId:s,classId:x.classId,schoolClass:{academicYearId:x.yearId}}});if(!section)throw new BadRequestException('Classroom scope is invalid.');return {schoolId:s,academicYearId:x.yearId,classId:x.classId,sectionId:x.sectionId}}
async homework(s:string|null,x:any){const q=await this.scope(s,x);return this.p.homework.findMany({where:q,include:{submissions:true},orderBy:{dueAt:'desc'}})}
async createHomework(s:string|null,x:any,d:any){const q=await this.scope(s,x);if(!d.title?.trim()||!d.subjectId||!d.dueAt)throw new BadRequestException('title, subjectId and dueAt are required.');const enrollments=await this.p.studentEnrollment.findMany({where:{...q,status:'ACTIVE'},select:{id:true}});return this.p.homework.create({data:{...q,subjectId:d.subjectId,title:d.title.trim(),description:d.description||null,dueAt:new Date(d.dueAt),status:d.status||'PUBLISHED',submissions:{create:enrollments.map(e=>({enrollmentId:e.id}))}},include:{submissions:true}})}
async updateHomework(s:string|null,x:any,d:any){const q=await this.scope(s,x);if(!await this.p.homework.findFirst({where:{id:x.id,...q}}))throw new NotFoundException('Homework not found.');if(d.submissionId)return this.p.homeworkSubmission.update({where:{id:d.submissionId},data:{status:d.submissionStatus,score:d.score==null?null:new Prisma.Decimal(d.score),feedback:d.feedback,submittedAt:d.submissionStatus==='SUBMITTED'?new Date():undefined}});return this.p.homework.update({where:{id:x.id},data:{...(d.title?{title:d.title}:{}),...(d.description!==undefined?{description:d.description}:{}),...(d.dueAt?{dueAt:new Date(d.dueAt)}:{}),...(d.status?{status:d.status}:{})}})}
async lessons(s:string|null,x:any){const q=await this.scope(s,x);return this.p.lessonPlan.findMany({where:q,orderBy:{scheduledDate:'desc'}})}
async createLesson(s:string|null,x:any,d:any){const q=await this.scope(s,x);if(!d.title||!d.objectives||!d.subjectId||!d.scheduledDate)throw new BadRequestException('title, objectives, subjectId and scheduledDate are required.');return this.p.lessonPlan.create({data:{...q,subjectId:d.subjectId,title:d.title,objectives:d.objectives,content:d.content||null,scheduledDate:new Date(d.scheduledDate),syllabusUnit:d.syllabusUnit||null,coveragePercent:Number(d.coveragePercent)||0,status:d.status||'DRAFT'}})}
async updateLesson(s:string|null,x:any,d:any){const q=await this.scope(s,x);if(!await this.p.lessonPlan.findFirst({where:{id:x.id,...q}}))throw new NotFoundException('Lesson plan not found.');return this.p.lessonPlan.update({where:{id:x.id},data:{...(d.status?{status:d.status}:{}),...(d.approvalComment!==undefined?{approvalComment:d.approvalComment}:{}),...(d.coveragePercent!==undefined?{coveragePercent:Number(d.coveragePercent)}:{})}})}
async announcements(s:string|null,x:any){const q=await this.scope(s,x);return this.p.classAnnouncement.findMany({where:q,orderBy:{createdAt:'desc'}})}
async createAnnouncement(s:string|null,x:any,d:any){const q=await this.scope(s,x);if(!d.title||!d.message)throw new BadRequestException('title and message are required.');const status=d.status||'PUBLISHED';return this.p.classAnnouncement.create({data:{...q,title:d.title,message:d.message,audience:d.audience||'PARENTS_AND_STUDENTS',status,publishedAt:status==='PUBLISHED'?new Date():null}})}
async updateAnnouncement(s:string|null,x:any,d:any){const q=await this.scope(s,x);if(!await this.p.classAnnouncement.findFirst({where:{id:x.id,...q}}))throw new NotFoundException('Announcement not found.');return this.p.classAnnouncement.update({where:{id:x.id},data:{status:d.status,publishedAt:d.status==='PUBLISHED'?new Date():undefined}})}
async calendar(s:string|null,x:any){const q=await this.scope(s,x);const [events,exams,homework,lessons]=await Promise.all([this.p.schoolEvent.findMany({where:{schoolId:q.schoolId,status:'ACTIVE'}}),this.p.exam.findMany({where:{schoolId:q.schoolId,academicYearId:q.academicYearId}}),this.p.homework.findMany({where:q}),this.p.lessonPlan.findMany({where:q})]);return [...events.map(v=>({id:v.id,type:'EVENT',title:v.title,date:v.startsAt})),...exams.map(v=>({id:v.id,type:'EXAM',title:v.name,date:v.startDate})),...homework.map(v=>({id:v.id,type:'HOMEWORK',title:v.title,date:v.dueAt})),...lessons.map(v=>({id:v.id,type:'LESSON',title:v.title,date:v.scheduledDate}))].filter(v=>v.date).sort((a,b)=>+new Date(a.date!)-+new Date(b.date!))}
async analysis(s:string|null,x:any){const q=await this.scope(s,x);const enrollments=await this.p.studentEnrollment.findMany({where:{...q,status:'ACTIVE'},include:{student:{include:{user:true}},attendance:true,marks:true}});return enrollments.map(e=>{const present=e.attendance.filter(a=>a.status==='PRESENT').length;const scores=e.marks.filter(m=>m.marksObtained!==null).map(m=>Number(m.marksObtained));return{id:e.id,student:`${e.student.user.firstName} ${e.student.user.lastName}`,admissionNumber:e.admissionNumber,attendancePercentage:e.attendance.length?Math.round(present/e.attendance.length*10000)/100:0,averageMarks:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length*100)/100:null,status:e.status}})}
async settings(s:string|null,x:any){await this.scope(s,x);return this.p.section.findUnique({where:{id:x.sectionId},include:{teacherAssignments:{where:{isActive:true},include:{teacher:{include:{user:true}}}}}})}
async updateSettings(s:string|null,x:any,d:any){await this.scope(s,x);return this.p.section.update({where:{id:x.sectionId},data:{...(d.name?{name:d.name}:{}),...(d.capacity!==undefined?{capacity:Number(d.capacity)}:{}),...(d.room!==undefined?{room:d.room}:{}),...(d.status?{status:d.status}:{})}})}
}
